from bs4 import BeautifulSoup
import requests

symbol_list = []

user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15'
headers = {'User-Agent': user_agent}


def create_list():
    page = 1
    offset = 0
    while offset < 5000:
        url = f'https://finance.yahoo.com/cryptocurrencies?count=100&offset={offset}'
        r = requests.get(url, headers=headers)
        soup = BeautifulSoup(r.text, "html.parser")
        table = soup.find("table", {"class": "W(100%)"})
        table_body = table.find("tbody", recursive=False)
        for tr in table_body:
            symbol = tr.find("a", {"data-test": "quoteLink"})
            symbol_list.append(symbol.string)
        page += 1
        print(f"page {page} done!")
        offset += 100

    return symbol_list


symbol_list_2 = ['BTC-USD', 'ETH-USD', 'USDT-USD', 'USDC-USD', 'BNB-USD', 'XRP-USD', 'BUSD-USD', 'ADA-USD', 'SOL-USD',
                 'DOGE-USD', 'MATIC-USD', 'DOT-USD', 'WTRX-USD', 'DAI-USD', 'TRX-USD', 'HEX-USD', 'SHIB-USD',
                 'WBTC-USD', 'UNI7083-USD', 'AVAX-USD', 'STETH-USD', 'LEO-USD', 'LTC-USD', 'LINK-USD', 'ATOM-USD',
                 'FTT-USD', 'ETC-USD', 'XLM-USD', 'CRO-USD', 'XMR-USD', 'NEAR-USD', 'ALGO-USD', 'QNT-USD', 'BCH-USD',
                 'BTCB-USD', 'TON11419-USD', 'VET-USD', 'LUNC-USD', 'FIL-USD', 'FLOW-USD', 'XCN18679-USD', 'EGLD-USD',
                 'FRAX-USD', 'HBAR-USD', 'ICP-USD', 'APE18876-USD', 'XTZ-USD', 'HT-USD', 'WBNB-USD', 'AAVE-USD',
                 'MANA-USD', 'SAND-USD', 'EOS-USD', 'MKR-USD', 'CHZ-USD', 'THETA-USD', 'APT21794-USD', 'USDP-USD',
                 'OKB-USD', 'KCS-USD', 'AXS-USD', 'BSV-USD', 'BIT11221-USD', 'TUSD-USD', 'ZEC-USD', 'HBTC-USD',
                 'BTTOLD-USD', 'USDD-USD', 'BTT-USD', 'XEC-USD', 'MIOTA-USD', 'USDN-USD', 'ETHW-USD', 'CAKE-USD',
                 'NEO-USD', 'GRT6719-USD', 'SNX-USD', 'HNT-USD', 'PAXG-USD', 'FTM-USD', 'NEXO-USD', 'RUNE-USD',
                 'GT-USD', 'LDO-USD', 'TWT-USD', 'CRV-USD', 'CSPR-USD', 'DASH-USD', 'KAVA-USD', 'FEI-USD', 'ENJ-USD',
                 'KLAY-USD', 'BAT-USD', 'XAUT-USD', 'STX4847-USD', 'ZIL-USD', 'XDC-USD', 'MINA-USD', 'RVN-USD',
                 'DCR-USD', 'MV-USD', 'USTC-USD', 'COMP5692-USD', 'ENS-USD', '1INCH-USD', 'WAVES-USD', 'CVX-USD',
                 'AR-USD', 'HOT2682-USD', 'XEM-USD', 'GUSD-USD', 'LRC-USD', 'CCXX-USD', 'OSMO-USD', 'CELO-USD',
                 'DFI-USD', 'KSM-USD', 'GMT18069-USD', 'LUNA20314-USD', 'BNX-USD', 'BTG-USD', 'ROSE-USD', 'ANKR-USD',
                 'GNO-USD', 'NXM-USD', 'YFI-USD', 'QTUM-USD', 'BAL-USD', 'JST-USD', 'GMX11857-USD', 'RSR-USD',
                 'GLM-USD', 'TFUEL-USD', 'KDA-USD', 'IOTX-USD', 'BTRST-USD', 'POLY-USD', 'WEMIX-USD', 'GALA-USD',
                 'CEL-USD', 'RPL-USD', 'LPT-USD', 'HUSD-USD', 'OMG-USD', 'T-USD', 'ONE3945-USD', 'AMP-USD', 'HIVE-USD',
                 'ZRX-USD', 'IOST-USD', 'FRTS-USD', 'GLMR-USD', 'ICX-USD', 'FLUX-USD', 'XYM-USD', 'CHSB-USD', 'WOO-USD',
                 'BORA-USD', 'SRM-USD', 'BRISE-USD', 'ONT-USD', 'LN-USD', 'LUSD-USD', 'WAXP-USD', 'SUSHI-USD',
                 'NFT9816-USD', 'RBN-USD', 'VVS-USD', 'XCH-USD', 'ZEN-USD', 'ZEON-USD', 'SC-USD', 'STORJ-USD',
                 'MDX8335-USD', 'OP-USD', 'SXP-USD', 'KNC-USD', 'AUDIO-USD', 'UMA-USD', 'ABBC-USD', 'SYN12147-USD',
                 'SCRT-USD', 'DESO-USD', 'MXC-USD', 'PLA7461-USD', 'BABYDOGE-USD', 'SLP-USD', 'REEF-USD', 'INJ-USD',
                 'IMX10603-USD', 'EWT-USD', 'ELON-USD', 'ASTR-USD', 'DGB-USD', 'SKL-USD', 'SOLO-USD', 'CKB-USD',
                 'ERG-USD', 'PUNDIX-USD', 'EURS-USD', 'DAO-USD', 'MED-USD', 'METIS-USD', 'LSK-USD', 'CVC-USD',
                 'REN-USD', 'VGX-USD', 'REQ-USD', 'COTI-USD', 'RNDR-USD', 'KEEP-USD', 'UQC-USD', 'VUSDC-USD',
                 'CEEK-USD', 'LOOKS-USD', 'USDX6651-USD', 'OCEAN-USD', 'BTCST-USD', 'NU-USD', 'FXS-USD', 'ONG3217-USD',
                 'CELR-USD', 'WIN-USD', 'TRIBE-USD', 'HUM-USD', 'PHA-USD', 'DYDX-USD', 'PYR-USD', 'VERI-USD', 'VLX-USD',
                 'SNT-USD', 'SSV-USD', 'RKN-USD', 'XNO-USD', 'RLC-USD', 'LYXE-USD', 'ARDR-USD', 'FX-USD', 'WVLX-USD',
                 'SYS-USD', 'MVL-USD', 'AVINOC-USD', 'API3-USD', 'MX-USD', 'PROM-USD', 'ORBS-USD', 'POWR-USD',
                 'UOS-USD', 'DAG-USD', 'GTN-USD', 'STEEM-USD', 'PEOPLE-USD', 'SPELL-USD', 'ACA-USD', 'SAFE3918-USD',
                 'NMR-USD', 'QUACK-USD', 'RACA-USD', 'BNT-USD', 'SCHO-USD', 'CTSI-USD', 'DENT-USD', 'ANY-USD',
                 'CTC-USD', 'CFX-USD', 'XYO-USD', 'FUN-USD', 'XPRT-USD', 'BICO-USD', 'CHR-USD', 'ARRR-USD', 'TEL-USD',
                 'FWT-USD', 'EUROC-USD', 'WRX-USD', 'CFG-USD', 'STRAX-USD', 'GAL11877-USD', 'REP-USD', 'ASD-USD',
                 'LOCUS-USD', 'RAD-USD', 'CTK-USD', 'QKC-USD', 'RAY-USD', 'EVER-USD', 'WEVER-USD', 'OGN-USD',
                 'SUSD-USD', 'RENBTC-USD', 'TRR-USD', 'H2O19091-USD', 'C98-USD', 'STPT-USD', 'AURORA14803-USD',
                 'TRAC-USD', 'BSW-USD', 'EPS8938-USD', 'ELF-USD', 'SFUND-USD', 'ANT-USD', 'BFC7817-USD', 'STMX-USD',
                 'SURE-USD', 'MPL-USD', 'JOE-USD', 'CBG-USD', 'MTL-USD', 'REV2135-USD', 'OXT-USD', 'XCAD-USD',
                 'RBTC-USD', 'UTK-USD', 'LOOM-USD', 'MOB-USD', 'FORTH-USD', 'LQTY-USD', 'MNW-USD', 'FET-USD',
                 'MAGIC14783-USD', 'SUN-USD', 'ORC-USD', 'NKN-USD', 'VBUSD-USD', 'STG18934-USD', 'VTHO-USD', 'AGIX-USD',
                 'MOVR-USD', 'EFI-USD', 'ACH-USD', 'ADS-USD', 'MAID-USD', 'CORE-USD', 'VAI-USD', 'WOZX-USD',
                 'AERGO-USD', 'XVS-USD', 'DERO-USD', 'SSX-USD', 'XWC-USD', 'NEST-USD', 'TLM-USD', 'BLOK-USD', 'RLY-USD',
                 'XSGD-USD', 'ETN-USD', 'XVG-USD', 'GHST-USD', 'DAWN-USD', 'BETA-USD', 'CUSD-USD', 'SANTOS-USD',
                 'MANC-USD', 'ARK-USD', 'PERP-USD', 'DIVI-USD', 'STRK-USD', 'KRD-USD', 'META-USD', 'AXEL-USD', 'IQ-USD',
                 'BITCI-USD', 'ALPHA-USD', 'SUPER8290-USD', 'SPS-USD', 'UFO10729-USD', 'DUSK-USD', 'BOBA-USD',
                 'BOND-USD', 'WXT-USD', '1ECO-USD', 'MFT-USD', 'AMPL-USD', 'RIF-USD', 'NEBL-USD', 'ONUS-USD', 'DPI-USD',
                 'HEDG-USD', 'ALICE-USD', 'MBOX-USD', 'TLOS-USD', 'MBL-USD', 'SOFI-USD', 'PRO-USD', 'POLS-USD',
                 'TT-USD', 'ERN-USD', 'BAKE-USD', 'RSS3-USD', 'OUSD-USD', 'YFII-USD', 'VEGA-USD', 'CON-USD', 'MUSD-USD',
                 'ALPACA-USD', 'VRA-USD', 'BADGER-USD', 'SFP-USD', 'KUNCI-USD', 'ARPA-USD', 'LCX-USD', 'LTO-USD',
                 'MLN-USD', 'KP3R-USD', 'SAITAMA20513-USD', 'QRDO-USD', 'COCOS-USD', 'POND-USD', 'IDEX-USD', 'EXRD-USD',
                 'DAR-USD', 'DEP-USD', 'TIME-USD', 'CBK-USD', 'HUNT-USD', 'WMT-USD', 'TOMO-USD', 'CLV-USD', 'KLV-USD',
                 'DKA-USD', 'AETHC-USD', 'AVA-USD', 'BAND-USD', 'YOOSHI-USD', 'ORN-USD', 'ASTRAFER-USD', 'XMON-USD',
                 'GXC-USD', 'LAZIO-USD', 'ILV-USD', 'WAN-USD', 'AUCTION-USD', 'KMD-USD', 'AMA21168-USD', 'CEUR-USD',
                 'ALPINE-USD', 'CRE-USD', 'YGG-USD', 'VUSDT-USD', 'MOC-USD', 'AIOZ-USD', 'AOG-USD', 'FLM-USD',
                 'TRB-USD', 'CET-USD', 'BZZ-USD', 'STRM17464-USD', 'DIA-USD', 'LINA7102-USD', 'TROY-USD',
                 'VOLT19650-USD', 'ALCX-USD', 'MCT16946-USD', 'CENNZ-USD', 'KAI-USD', 'BTS-USD', 'MASK8536-USD',
                 'BCD-USD', 'NOIA-USD', 'ELA-USD', 'WKAI-USD', 'SWEAT-USD', 'CPOOL-USD', 'CLT-USD', 'ANC8857-USD',
                 'RSV-USD', 'XPR-USD', 'AE-USD', 'USDK-USD', 'PORTO-USD', 'AKT-USD', 'RFR-USD', 'KILT-USD', 'RARI-USD',
                 'ICHI-USD', 'UBT-USD', 'MONA-USD', 'REI19819-USD', 'HARD-USD', 'ALEPH-USD', 'LIT6833-USD', 'LON-USD',
                 'UPP-USD', 'SERO-USD', 'FCTFCT2-USD', 'AQT-USD', 'STARL-USD', 'SBD-USD', 'FORT20622-USD', 'BMX-USD',
                 'ULT-USD', 'TVK-USD', 'UNFI-USD', 'PIVX-USD', 'HOO-USD', 'WNXM-USD', 'MC-USD', 'BLZ-USD', 'MEV-USD',
                 'FIRO-USD', 'ATA-USD', 'FIO-USD', 'HANDY-USD', 'TKO-USD', 'BEL-USD', 'ONIT-USD', 'RAMP-USD', 'CHO-USD',
                 'QI9288-USD', 'PSG-USD', 'HI-USD', 'TRU7725-USD', 'HYDRA-USD', 'IRIS-USD', 'RGT-USD', 'EUM-USD',
                 'FARM-USD', 'DG15478-USD', 'CITY10049-USD', 'CLO-USD', 'SOUL-USD', 'COL-USD', 'GODS-USD', 'BURGER-USD',
                 'GRS-USD', 'PRE-USD', 'SAMO-USD', 'SWAP-USD', 'VETH-USD', 'GMT10180-USD', 'WING7048-USD',
                 'BIFI7311-USD', 'KEY-USD', 'FRONT-USD', 'ROUTE-USD', 'KIN-USD', 'ADX-USD', 'COS-USD', 'KOK-USD',
                 'DATA-USD', 'WTC-USD', 'QOM-USD', 'SDAO-USD', 'ATOLO-USD', 'MLK-USD', 'CULT-USD', 'BOSON-USD',
                 'GAS-USD', 'GTC10052-USD', 'MNGO-USD', 'KRT-USD', 'DFG19590-USD', 'SPA-USD', 'TPT-USD', 'SLND-USD',
                 'AGLD-USD', 'JASMY-USD', 'FIS-USD', 'RMRK-USD', 'OM-USD', 'AST-USD', 'SOS16463-USD', 'DVF-USD',
                 'ASM-USD', 'MAP-USD', 'CQT-USD', 'BNANA-USD', 'KAS-USD', 'BEAM-USD', 'MDT-USD', 'ZASH-USD', 'CHP-USD',
                 'COVAL-USD', 'LA-USD', 'CTXC-USD', 'LAT-USD', 'DX-USD', 'CHESS10974-USD', 'VXVS-USD', 'PIT-USD',
                 'VRSC-USD', 'PHB-USD', 'TITAN-USD', 'AION-USD', 'HNS-USD', 'AMO-USD', 'HTR-USD', 'BAR-USD', 'MITH-USD',
                 'WILD-USD', 'QUICK-USD', 'ALT10897-USD', 'NULS-USD', 'EGG-USD', 'CUDOS-USD', 'PNK-USD', 'TOKE-USD',
                 'HERO10778-USD', 'KAR-USD', 'AHT-USD', 'RISE15257-USD', 'GYEN-USD', 'GTO-USD', 'PLU-USD', 'HIGH-USD',
                 'LEVER-USD', 'DXD-USD', 'VXV-USD', 'CVP-USD', 'SAITO-USD', 'FIDA-USD', 'VOXEL-USD', 'MWC-USD',
                 'VIDT-USD', 'GET-USD', 'AKRO-USD', 'DNT-USD', 'BWO-USD', 'ALI16876-USD', 'SOLVE-USD', 'MARO-USD',
                 'ROOK-USD', 'BTM-USD', 'HEZ-USD', 'FRA-USD', 'MIX-USD', 'CUBE-USD', 'DOCK-USD', 'ARG-USD', 'XNC-USD',
                 'ALBT-USD', 'NSBT-USD', 'MSB-USD', 'GOC-USD', 'DORA-USD', 'BTSE-USD', 'APL-USD', 'PRQ-USD',
                 'YLD8066-USD', 'VITE-USD', 'MCRT-USD', 'GFI13967-USD', 'AMB-USD', 'BANANA8497-USD', 'DEXE-USD',
                 'NMC-USD', 'MIR7857-USD', 'MSOL-USD', 'FSN-USD', 'DEGO-USD', 'USDJ-USD', 'DF-USD', 'RARE11294-USD',
                 'BIDR-USD', 'DAD-USD', 'STC-USD', 'DREP-USD', 'NCT-USD', 'LBC-USD', 'BOA-USD', 'OOKI-USD', 'DDX-USD',
                 'PTU-USD', 'OAX-USD', 'FOX-USD', 'HDAO-USD', 'DVI-USD', 'VIB-USD', 'ABT-USD', 'GST16352-USD',
                 'EROWAN-USD', 'DERC-USD', 'DODO-USD', 'WICC-USD', 'MET-USD', 'KRL-USD', 'PPC-USD', 'RAI-USD',
                 'NWC-USD', 'HOPR-USD', 'GBYTE-USD', 'TREEB-USD', 'LTX-USD', 'OVR-USD', 'PNT5794-USD', 'TONE-USD',
                 'OXEN-USD', 'ACM8538-USD', 'SIX-USD', 'JUV-USD', 'MVC-USD', 'SHPING-USD', 'APX-USD', 'NIM-USD',
                 'AUTO-USD', 'BABY10334-USD', 'PNG-USD', 'EVZ-USD', 'BUX-USD', 'CTX-USD', 'WNCG-USD', 'FOR-USD',
                 'MLT-USD', 'QRL-USD', 'VTC-USD', 'IHC-USD', 'GEL-USD', 'NFTX-USD', 'STAKE-USD', 'DMD-USD', 'LOKA-USD',
                 'ZCN-USD', 'PROS8255-USD', 'DPR-USD', 'BTC2-USD', 'XHV-USD', 'SNM-USD', 'POR-USD', 'ZBC-USD',
                 'PEAK-USD', 'QSP-USD', 'SENSO-USD', 'TTT5514-USD', 'DEXT-USD', 'PDEX-USD', 'SDN-USD', 'WHALE-USD',
                 'PTS-USD', 'WABI-USD', 'HPT-USD', 'SUKU-USD', 'KAN-USD', 'ZKS-USD', 'IHF-USD', 'SWTH-USD', 'MATH-USD',
                 'LSS-USD', 'AURY-USD', 'BOO-USD', 'HOGE-USD', 'PERL-USD', 'ERC20-USD', 'INSTAR-USD', 'INTER-USD',
                 'PEEL-USD', 'AVT-USD', 'BASIC-USD', 'XEP-USD', 'UFT-USD', 'CAJ-USD', 'RFOX-USD', 'XCP-USD', 'GARI-USD',
                 'SCP-USD', 'VEED-USD', 'MINTME-USD', 'BF-USD', 'PZM-USD', 'PENDLE-USD', 'VINU15270-USD', 'CERE-USD',
                 'ADP-USD', 'TABOO-USD', 'CRTS-USD', 'AFC11532-USD', 'ALU-USD', 'THG-USD', 'URUS-USD', 'VBIT-USD',
                 'SOV-USD', 'SOC5126-USD', 'ARV-USD', 'GOG-USD', 'PUSH-USD', 'FUND-USD', 'NRG-USD', 'GMM-USD',
                 'ATM-USD', 'ATLAS-USD', 'VR-USD', 'CRPT-USD', 'NUM-USD', 'XOR-USD', 'GO-USD', 'DACXI-USD', 'GAFI-USD',
                 'HAI-USD', 'BSCPAD-USD', 'UNCX-USD', 'QASH-USD', 'APM-USD', 'VEE-USD', 'FST-USD', 'GENE13632-USD',
                 'GRID-USD', 'VID-USD', 'FOAM-USD', 'TEMCO-USD', 'BLCT-USD', 'IDRT-USD', 'PALLA-USD', 'RBC-USD',
                 'EL-USD', 'SLIM-USD', 'CREAM-USD', 'GAL-USD', 'ID-USD', 'NEER-USD', 'NYE-USD', 'XPX-USD', 'SOCKS-USD',
                 'SHILL-USD', 'QTCON-USD', 'KDAG-USD', 'PROB-USD', 'HIBS-USD', 'GHX-USD', 'ES-USD', 'MBS-USD',
                 'XDB-USD', 'MENGO-USD', 'BOR-USD', 'RAE-USD', 'OBSR-USD', 'PCX-USD', 'EPIC-USD', 'ASK-USD', 'VAL-USD',
                 'POLIS11213-USD', 'CYCLUB-USD', 'RING-USD', 'DGD-USD', 'CAPS-USD', 'DOGEDASH-USD', 'VRT-USD',
                 'SHFT-USD', 'AAB-USD', 'ZNN-USD', 'BAN-USD', 'ASR-USD', 'SOC-USD', 'GOM2-USD', 'SWASH-USD', 'OG-USD',
                 'BTR4167-USD', 'CRU-USD', 'POSI-USD', 'SATT-USD', 'LBL-USD', 'TIFI-USD', 'EMRX-USD', 'BEPRO-USD',
                 'BONE11865-USD', 'CIV11345-USD', 'ZYN-USD', 'HAPI-USD', 'MAPS-USD', 'JUP-USD', 'PEX16104-USD',
                 'IPAD-USD', 'DIME-USD', 'QLC-USD', 'MCB-USD', 'GF15585-USD', 'ARIA20-USD', 'WIKEN-USD', 'CAS-USD',
                 'GULF-USD', 'CGG-USD', 'PART-USD', 'CELL-USD', 'MANDOX19747-USD', 'VDAI-USD', 'RAINI-USD', 'TORN-USD',
                 'RDD-USD', 'INV-USD', 'EDG5274-USD', 'MONA7866-USD', 'LOG-USD', 'BIOT-USD', 'EDG-USD', 'SHIRYO-USD',
                 'KASTA-USD', 'VIDYA-USD', 'XMC-USD', 'DVPN-USD', 'DRGN-USD', 'BETU-USD', 'BTRS-USD', 'ONE-USD',
                 'ASTA-USD', 'SWFTC-USD', 'WOM19623-USD', 'EQUAD-USD', 'WOOP-USD', 'POLK-USD', 'MYST-USD', 'PXP-USD',
                 'XDEFI-USD', 'XNO8368-USD', 'TRV-USD', 'XED-USD', 'MHC-USD', 'TRA-USD', 'SIDUS-USD', 'UPUNK-USD',
                 'TRVL-USD', 'POOLZ-USD', 'ATRI-USD', 'REAP-USD', 'PKT9523-USD', 'MTA-USD', 'SYLO-USD', 'MOBI-USD',
                 'NAKA-USD', 'SIGNA-USD', 'HEGIC-USD', 'PSTAKE-USD', 'SHR-USD', 'KYL-USD', 'TOWN-USD', 'DFA-USD',
                 'CBX-USD', 'TEN-USD', 'CCT-USD', 'TNC5524-USD', 'BUY11750-USD', 'CRP-USD', 'MRS21178-USD', 'WOM-USD',
                 'EPIK-USD', 'PKF-USD', 'VELO-USD', 'INSUR-USD', 'BFT-USD', 'VALOR-USD', 'CARD-USD', 'XWG-USD',
                 'JOB-USD', 'GMEE-USD', 'FUSE-USD', 'GRIN-USD', 'PAC-USD', 'O3-USD', 'NEX-USD', 'ETHAX-USD', 'CHNG-USD',
                 'BLY-USD', 'BCN-USD', 'NBS-USD', 'MOF-USD', 'WRLD-USD', 'PBR-USD', 'DHT-USD', 'HC-USD', 'NEW-USD',
                 'NXS-USD', 'VLTC-USD', 'ILC-USD', 'STOS-USD', 'VIA-USD', 'REVV-USD', 'FKX-USD', 'VLINK-USD', 'SAN-USD',
                 'TON-USD', 'PMON-USD', 'DERI-USD', 'GLCH-USD', 'ZANO-USD', 'STRX-USD', 'XTM-USD', 'TKP-USD', 'NAV-USD',
                 'JGN-USD', 'DEHUB-USD', 'AXIS8849-USD', 'MTV-USD', 'DOBO-USD', 'BITCNY-USD', 'HAM-USD', 'OOE-USD',
                 'AWC-USD', 'BIP-USD', 'MEETONE-USD', 'SALT-USD', 'KMA-USD', 'STACK9201-USD', 'RDN-USD', 'DYP-USD',
                 'BAO-USD', 'DTEP-USD', 'OGV-USD', 'SFI-USD', 'GOVI-USD', 'SHX-USD', 'CIRUS-USD', 'WOW-USD', 'VEMP-USD',
                 '1WO-USD', 'SEELE-USD', 'NAP-USD', 'IDIA-USD', 'LNC-USD', 'SWP-USD', 'CUMMIES-USD', 'GSWAP-USD',
                 'IGNIS-USD', 'SNC-USD', 'ZLW-USD', 'BAAS-USD', 'ZIG-USD', 'FCT-USD', 'DFL-USD', 'FB11308-USD',
                 'AGRS-USD', 'NOW-USD', 'NVT-USD', 'TCT-USD', 'CGT-USD', 'DFYN-USD', 'WWY-USD', 'GEEQ-USD', 'MUSE-USD',
                 'BRWL-USD', 'ERA-USD', 'MINT10977-USD', 'GST21152-USD', 'LIKE-USD', 'DEL-USD', 'COV-USD', 'PPT-USD',
                 'MOD-USD', 'OTO-USD', 'VSP-USD', 'GST20236-USD', 'PAY-USD', 'DLC21849-USD', 'KARMA-USD', 'TARA-USD',
                 'OPUL-USD', 'MTH-USD', 'NHT-USD', 'BHP-USD', 'DXL-USD', 'CHI-USD', 'SIN12813-USD', 'NGM-USD',
                 'UFC11533-USD', 'MONI-USD', 'VSYS-USD', 'XEND-USD', 'MAHA-USD', 'ABYSS-USD', 'PRISM-USD', 'NXT-USD',
                 'LITH-USD', 'FLX9493-USD', 'TNB-USD', 'ENQ-USD', 'GRC-USD', 'SAFEMOON-USD', 'XRT-USD', 'BELT-USD',
                 'ROOBEE-USD', 'XCHF-USD', 'BTNT-USD', 'BTCP-USD', 'BLP-USD', 'OLT-USD', 'TOWER-USD', 'KALM-USD',
                 'DSLA-USD', 'CARBON-USD', 'TULIP-USD', 'MATTER-USD', 'BP12293-USD', 'RVLT-USD', 'SRK-USD',
                 'MBN7059-USD', 'TRIX-USD', 'ARA11738-USD', 'SAFE-USD', 'YAM7131-USD', 'UNO8875-USD', 'TOKO-USD',
                 'ORAI-USD', 'XFC-USD', 'PI-USD', 'ADK-USD', 'SKEY-USD', 'MOOV-USD', 'DOV-USD', 'JAM17852-USD',
                 '1ART-USD', 'ZOO9488-USD', 'RTH-USD', 'SD-USD', 'LGCY-USD', 'NFTART-USD', 'DIP-USD', 'MITX-USD',
                 'HOD-USD', 'GPX-USD', 'NYAN-USD', 'RVF-USD', 'CTCN-USD', 'SUTER-USD', 'EKTA-USD', 'DTX-USD',
                 'SATA-USD', 'TAU-USD', 'ORS-USD', 'KONO-USD', 'SKY-USD', 'UPI-USD', 'LAMB-USD', 'GMCOIN-USD',
                 'BOLT-USD', 'GNY-USD', 'PING-USD', 'KMON-USD', 'GOZ-USD', 'EOSC-USD', 'VCF-USD', 'VSXP-USD',
                 'GTON-USD', 'REV-USD', 'KAT-USD', 'RAZOR-USD', 'COLX-USD', 'PICKLE-USD', 'FREE-USD', 'K21-USD',
                 'SFD-USD', 'BAX-USD', 'BCDT-USD', 'GAME-USD', 'GHOST-USD', 'OOKS-USD', 'NAS-USD', 'SNTVT-USD',
                 'ONSTON-USD', 'BEND-USD', 'ETP-USD', 'AOA-USD', 'VEST-USD', 'IFC-USD', 'XFT-USD', 'EOSDT-USD',
                 'ERSDL-USD', 'DEFIT-USD', 'CLOAK-USD', 'DBC-USD', 'LABS-USD', 'ZEE-USD', 'TKN-USD', 'TFT-USD',
                 'SPIRIT-USD', 'LUA-USD', 'BNC8705-USD', 'DAFI-USD', 'CRA-USD', 'KUBE-USD', 'LCC-USD', 'VDOT-USD',
                 'DGX-USD', 'NFTY-USD', 'ICE13133-USD', 'MFG-USD', 'DOE-USD', 'SHROOM-USD', 'CPT-USD', 'SHA-USD',
                 'PRIMATE-USD', 'RFUEL-USD', 'LAND11245-USD', 'SARCO-USD', 'METAPETS-USD', 'SCC3986-USD', 'SIB-USD',
                 'DIO-USD', 'PSP-USD', 'SWRV-USD', 'FCD18994-USD', 'METAG-USD', 'BIR-USD', 'FRIN-USD', 'PMGT-USD',
                 'SMT-USD', 'VDG-USD', 'ROCO12653-USD', 'HORD-USD', 'BTCZ-USD', 'SWINGBY-USD', 'UBQ-USD', 'ACT-USD',
                 'DDIM-USD', 'FRM-USD', 'NFTD12137-USD', 'MEME6597-USD', 'BRG-USD', 'GNX-USD', 'EMC2-USD', 'UBXT-USD',
                 'STRP-USD', 'UBX-USD', 'POA-USD', 'ISIKC-USD', 'CHICKS-USD', 'THN-USD', 'SPC-USD', 'HZN-USD',
                 'BIFI8132-USD', 'MINT8423-USD', 'NPXSXEM-USD', 'DIGG-USD', 'BSCS-USD', 'ISP-USD', 'LYM-USD',
                 'AEON-USD', 'NEXT14841-USD', 'DCN-USD', 'RYOSHI-USD', 'XBY-USD', 'TEER-USD', 'OXY-USD', 'MIR-USD',
                 'WEST-USD', 'MOVEZ-USD', 'ACK-USD', 'STARS-USD', 'SFT-USD', 'AZY-USD', 'XLT-USD', '0XBTC-USD',
                 'REPO-USD', 'WOOF-USD', 'PLAY-USD', 'LBTC-USD', 'SPARTA-USD', 'XPM-USD', 'ITGR-USD', 'IQN-USD',
                 'IDV-USD', 'EXM-USD', 'FTC-USD', 'VAB-USD', 'BMON-USD', 'DEC-USD', 'ONION-USD', 'EM-USD', 'RCN-USD',
                 'EGT-USD', 'KROM-USD', 'DOGGY-USD', 'MASQ-USD', 'BLOCK-USD', 'BHC-USD', 'TAROT-USD', 'SCCP-USD',
                 'PORNROCKET-USD', 'PRT-USD', 'SPH-USD', 'BLT-USD', 'LIME-USD', 'MEME-USD', 'SLRS-USD', 'WGR-USD',
                 'TRADE10465-USD', 'SENATE-USD', 'OPEN13206-USD', 'NLG-USD', 'SKILL-USD', 'SWOP-USD', 'PLY19268-USD',
                 'WEBD-USD', 'SEON-USD', 'ZUSD8772-USD', 'LIKE10891-USD', 'PAID-USD', 'XY-USD', 'TX-USD', 'LEVL-USD',
                 'BCMC-USD', 'KOM-USD', 'TENT-USD', 'CVT-USD', 'NFTB-USD', 'WOMBAT-USD', 'XAUR-USD', 'SPORT20390-USD',
                 'EQZ-USD', 'RPG12221-USD', 'UNB-USD', 'COVA-USD', 'NORD-USD', 'LAYER-USD', 'SMI-USD', 'STANDARD-USD',
                 'CWS-USD', 'ATT-USD', 'TOP-USD', 'BIX-USD', 'KT-USD', 'ARDX-USD', 'FO-USD', 'INT-USD', 'SHARD-USD',
                 'CRON-USD', 'IDLE-USD', 'ALY-USD', 'HOT-USD', 'RAVEN-USD', 'DPS-USD', 'KTN-USD', 'TKING-USD',
                 'THC-USD', 'CMERGE-USD', 'DRF-USD', 'PNY-USD', 'CBC-USD', 'CV-USD', 'CMT2246-USD', 'TRIAS-USD',
                 'EBEN-USD', 'XFL-USD', 'PLOT-USD', 'FINA-USD', 'MTC-USD', '42-USD', 'OWC-USD', 'DPET-USD', 'CONV-USD',
                 'ACE9792-USD', 'YAXIS-USD', 'MAN-USD', 'BIN-USD', 'FEVR-USD', 'C20-USD', 'LOWB-USD', 'IMT-USD',
                 'ADAPAD-USD', 'ESD-USD', 'EFX-USD', 'NABOX-USD', 'YAE-USD', 'SKU-USD', 'SRN-USD', 'BMP-USD', 'BCA-USD',
                 'STAK9441-USD', 'PAI-USD', 'ODDZ-USD', 'EXRN-USD', 'PLANETS-USD', 'ZMN-USD', 'BDP8708-USD',
                 'HOTCROSS-USD', 'OLE-USD', 'LUFC-USD', 'BBS18184-USD', 'DON9643-USD', 'YEC-USD', 'REVO-USD', 'RPG-USD',
                 'FCON-USD', 'LBA-USD', 'SMARTCREDIT-USD', 'GZONE-USD', 'DAX-USD', 'MAX5067-USD', 'MRX-USD', 'TMTG-USD',
                 'GHOST5475-USD', 'IBFK-USD', 'BXC-USD', 'PLR-USD', 'SYNC-USD', 'XCASH-USD', 'TRUE-USD', 'TXA-USD',
                 'TFBX-USD', 'CPC-USD', 'FAIR2366-USD', 'KINGSHIB-USD', 'LIFE-USD', 'OCTO-USD', 'EDEN-USD', 'IDNA-USD',
                 'NIF-USD', 'PLA4242-USD', 'CS-USD', 'LBP-USD', 'PUMLX-USD', 'MSTR16948-USD', 'VEX-USD', 'JULD-USD',
                 'AMLT-USD', 'DNA5234-USD', 'FARA-USD', 'ICNQ-USD', 'MASS-USD', 'DESU-USD', 'GLEEC-USD', 'BBANK-USD',
                 'VIDY-USD', 'TONS-USD', 'GMPD-USD', 'CMERGE14794-USD', 'VIN-USD', 'GTH-USD', 'SHI-USD', 'LIGHT-USD',
                 'EUNO-USD', 'PUT-USD', 'DINO10777-USD', 'YBO-USD', 'BMI-USD', 'PACOCA-USD', 'QRK-USD', 'GIO-USD',
                 'FEAR-USD', 'WNT-USD', 'IOI-USD', 'VIG-USD', 'DEXA-USD', 'CND-USD', 'SHND-USD', 'ELEC-USD', 'MIT-USD',
                 'SLICE-USD', 'UNISTAKE-USD', 'TAD-USD', 'EPK-USD', 'STARSHIP-USD', 'SNB-USD', 'BLANK-USD',
                 'DRM5837-USD', 'OMNI-USD', 'BCUBE-USD', 'BIS-USD', 'EVRY-USD', 'BTX-USD', 'FNDZ-USD', 'GMB3819-USD',
                 'OPCT-USD', 'YOU-USD', 'GCOIN-USD', 'ELMON-USD', 'HPB-USD', 'PKR-USD', 'PXC-USD', 'MDA-USD', 'FIN-USD',
                 'XRUNE-USD', 'XCV-USD', 'TUP-USD', 'TCP9416-USD', 'BLAST9967-USD', 'CHESS-USD', 'CCX-USD', 'BRZE-USD',
                 'MPH7742-USD', 'ARCONA-USD', 'MIST9218-USD', 'XHI-USD', 'AOG16679-USD', 'PLC-USD', 'STRONG-USD',
                 'KICK-USD', 'SILVA-USD', 'PAWTH-USD', 'XTAG-USD', 'WHITE-USD', 'CRWNY-USD', 'BOTTO-USD', 'GVT-USD',
                 'LET-USD', 'GSTS-USD', 'YOP-USD', 'HEC17462-USD', 'CYC-USD', 'UAXIE-USD', 'GHNY-USD', 'OLY-USD',
                 'DUCK8063-USD', 'EMC-USD', 'HAND-USD', 'HAWK-USD', 'BUY-USD', 'GALO-USD', 'WSG-USD', 'BONDLY-USD',
                 'SPFC-USD', 'AIT-USD', 'CTI-USD', 'BLK-USD', 'BIST-USD', 'BRD-USD', 'KCCPAD-USD', 'ZAP-USD', 'XMV-USD',
                 'DAVIS-USD', 'TIPS-USD', 'GLC-USD', 'SMART-USD', 'DMG-USD', 'PROPS-USD', 'YFL-USD', 'XPN-USD',
                 'MIBR-USD', 'SOLX-USD', 'HYVE-USD', 'YOYOW-USD', 'HNST-USD', 'BOLLY-USD', 'AGA-USD', 'UFR-USD',
                 'LOCG-USD', 'EFC-USD', 'AM-USD', 'BLKC-USD', 'FYD-USD', 'LAUNCH-USD', 'MTN-USD', 'HMQ-USD', 'DAV-USD',
                 'RHYTHM-USD', 'KEX-USD', 'UCA-USD', 'SWACE-USD', 'PERI-USD', 'SAUBER-USD', 'BIRD7795-USD', 'PHNX-USD',
                 'INXT-USD', 'KLO-USD', 'REDPANDA-USD', 'QDAO-USD', 'VIBE-USD', 'SPORE9468-USD', 'CAT-USD', 'IGG-USD',
                 'GTC-USD', 'FINE-USD', 'STPL-USD', 'BHD-USD', 'TXL-USD', 'SWG-USD', 'AVL-USD', 'CHAT-USD', 'UCH-USD',
                 'OPIUM-USD', 'CORN7806-USD', 'XDN-USD', 'COMBO-USD', 'MOBIC-USD', 'RYO-USD', 'SNY-USD', 'ZDR-USD',
                 'TRADE-USD', 'OCN-USD', 'SHOPX-USD', 'PLF-USD', 'DAPP-USD', 'CRBN-USD', 'KABY-USD', 'DDD-USD',
                 'KGO-USD', 'GRLC-USD', 'GEN-USD', 'DWEB-USD', 'XNL-USD', 'DMT-USD', 'WATCH-USD', 'DOUGH-USD',
                 'OPEN-USD', 'ETHPAD-USD', 'SUMO-USD', 'PMA-USD', 'VPP-USD', 'VNLA-USD', 'LANA-USD', 'IF-USD',
                 'UDO-USD', 'HTML-USD', 'XSR4818-USD', 'GOF-USD', 'GLQ-USD', 'DAPPX-USD', 'WAG-USD', 'RAID21527-USD',
                 'GFI-USD', 'ZEFU-USD', 'GRG-USD', 'STND-USD', 'PWAR-USD', 'HIT-USD', 'NBOT-USD', 'ASTRO12120-USD',
                 'HGOLD-USD', 'OCE-USD', 'ZOON-USD', 'BITS659-USD', 'POT-USD', 'BANK8612-USD', 'HUSH-USD', 'HVN-USD',
                 '2CRZ-USD', 'XMX-USD', 'NYC-USD', 'SKM-USD', 'UMB-USD', 'DNXC-USD', 'PBX-USD', 'GSC-USD', 'TERA-USD',
                 'XMY-USD', 'STV-USD', 'QCH-USD', 'HAKKA-USD', 'FYP-USD', 'PVU-USD', 'VDL-USD', 'KAMPAY-USD', 'NAX-USD',
                 '1-UP-USD', 'LXT-USD', 'CLR-USD', 'URQA-USD', 'OIN-USD', 'HUSL11448-USD', 'XPD-USD', 'APIX-USD',
                 'CSM-USD', 'STEP17010-USD', 'KCASH-USD', 'ALA12649-USD', 'SETH-USD', 'WPR-USD', 'APY-USD', 'PXL-USD',
                 'PST-USD', 'HGET-USD', 'FAM-USD', 'SAKE-USD', 'XBC-USD', 'BRKL-USD', 'NIOX-USD', 'BASE-USD',
                 'WELT-USD', 'MND-USD', 'LFG-USD', 'BGL-USD', 'JRT-USD', 'ATL-USD', 'ESS-USD', 'IETH-USD', 'ORB-USD',
                 'PFL-USD', 'GDAO-USD', 'CFI-USD', 'CHEEMS-USD', 'X8X-USD', 'FRKT-USD', 'UMASK-USD', 'USDS-USD',
                 'MARSH-USD', 'IXC-USD', 'FIU-USD', 'NAFT-USD', 'ANRX-USD', 'RNT-USD', 'RVC-USD', 'RUFF-USD', 'DTA-USD',
                 'GEO5590-USD', 'NCDT-USD', 'SCC-USD', 'SNET-USD', 'PPAY-USD', 'WNDR-USD', 'NAVI-USD', 'OK-USD',
                 'CUT-USD', 'CANDY11083-USD', 'RAZE-USD', 'CANN-USD', 'ALL-USD', 'RBLX-USD', 'APL7638-USD', 'AMON-USD',
                 'MFC16913-USD', 'PETS-USD', 'XLA-USD', 'ASAP-USD', 'UIP-USD', 'SMT11821-USD', 'RAINBOW-USD',
                 'TERC-USD', 'LDOGE-USD', 'MDS-USD', 'SAM14020-USD', 'APPC-USD', 'XCUR-USD', 'STA-USD', 'TOK12302-USD',
                 'ARES-USD', 'XIO-USD', 'LINKA-USD', 'NCASH-USD', 'LUC-USD', 'SCR-USD', 'PHI-USD', 'AG8-USD', 'D-USD',
                 'STM-USD', 'FLP-USD', 'SWT-USD', 'CRW-USD', 'DVP-USD', 'BANKER-USD', 'DOWS-USD', 'SIN-USD', 'AIRT-USD',
                 'FTX-USD', 'ATP-USD', 'BTB-USD', 'DPY-USD', 'ADB-USD', 'BEER-USD', 'MVP-USD', 'ADM-USD', 'AITRA-USD',
                 'KRB-USD', 'CRP11387-USD', 'DDOS-USD', 'HELMET-USD', 'LANC-USD', 'COFI-USD', 'UMX-USD', 'YETIC-USD',
                 'RHT-USD', 'COGI-USD', 'CAI-USD', 'FCL-USD', 'CNTR-USD', 'ETHYS-USD', 'TCH3806-USD', 'BOX-USD',
                 'LKR-USD', 'AME-USD', 'CDT-USD', 'CHX-USD', 'RINGX-USD', 'PLSPAD-USD', 'CSP-USD', 'DHV-USD',
                 'DOSE-USD', 'LZ-USD', 'DEPAY-USD', 'OST-USD', 'TRC-USD', 'TRL12350-USD', 'SPO-USD', 'UUU-USD',
                 'AZ-USD', 'ONX12816-USD', 'PPBLZ-USD', 'TH-USD', 'S4F-USD', 'GLS-USD', '8PAY-USD', 'ODIN-USD',
                 'WINGS-USD', 'DZG-USD', 'VBCH-USD', 'LCS-USD', 'SMLY-USD', 'DEV-USD', 'HEAT-USD', 'EDN-USD', 'BLU-USD',
                 'ZCL-USD', 'CURE-USD', 'FNT-USD', 'EBST-USD', 'SUB-USD', 'TOC-USD', 'SFX-USD', 'COOK-USD',
                 'BLINK7784-USD', 'PAR-USD', 'UBXS-USD', 'HYDRO-USD', 'BOB-USD', 'FORM-USD', 'MIN12787-USD', 'XTP-USD',
                 'EZ-USD', 'KART-USD', 'KTON-USD', 'RATING-USD', 'LFW-USD', 'OMC10228-USD', 'LEG-USD', 'RED-USD',
                 'DOP9675-USD', 'PAK-USD', 'COR-USD', 'SWM-USD', 'TIDAL-USD', 'KANGAL-USD', 'IPX-USD', 'XPNET-USD',
                 'FSW-USD', 'METAX-USD', 'BZNT-USD', 'SPD2828-USD', 'SDT8299-USD', 'AYA-USD', 'CORA-USD', 'VGW-USD',
                 'TTN-USD', 'PCNT-USD', 'GARD-USD', 'LML-USD', 'VSO-USD', 'BXY-USD', 'DAC-USD', 'UTU-USD', 'HBX-USD',
                 'TRTL-USD', 'SKB-USD', 'APYS-USD', 'XRC-USD', 'ETHA-USD', 'PAINT-USD', 'SNOW-USD', 'TYC-USD',
                 'BTO-USD', 'WGP-USD', 'TELOS-USD', 'DIT-USD', 'RET-USD', 'HYC-USD', 'BAC-USD', 'ORION-USD',
                 'RUNE9905-USD', 'CLAM15233-USD', 'SHIBX-USD', 'GLINT-USD', 'DOGEC-USD', 'TYPE-USD', 'EOSDAC-USD',
                 'ASPO-USD', 'FXF-USD', 'BBP-USD', 'GMAT-USD', 'TRAVA-USD', 'CRX-USD', 'SIGN-USD', 'FUEL-USD',
                 'HTDF-USD', 'ANW-USD', 'CNB-USD', 'SPUME-USD', 'PASS-USD', 'BNTY-USD', 'WTN-USD', 'DAPS-USD',
                 'BCPT-USD', 'BPS-USD', 'EVED-USD', 'NANJ-USD', 'APN-USD', 'SN-USD', 'BATH-USD', 'BANCA-USD',
                 'VEIL-USD', 'IBP-USD', 'WISH-USD', 'PXG-USD', 'CAPP-USD', 'SPWN-USD', 'GCC1531-USD', 'INK-USD',
                 'UBEX-USD', 'LEDU-USD', 'A-USD', 'NRV-USD', 'EVX-USD', 'N1-USD', 'BIRD-USD', 'PTF-USD', 'X42-USD',
                 'SAO-USD', 'PEPS-USD', 'REM-USD', 'CVR-USD', 'KTLYO-USD', 'MANNA-USD', 'FNB-USD', 'MAT-USD', 'NOV-USD',
                 'UDOO-USD', 'ROOM-USD', 'WAB-USD', 'VIT-USD', 'MOTO-USD', 'EQL-USD', 'CERES-USD', 'LEV11534-USD',
                 'POLI-USD', 'RXS-USD', 'IDEA-USD', 'TIP13138-USD', 'IHT-USD', 'PINK-USD', 'XIV-USD', 'DOS-USD',
                 'DYNA-USD', 'AXPR-USD', 'AAC-USD', 'NNI-USD', 'PIN-USD', 'PTOY-USD', 'ROYA-USD', 'XLAB-USD', 'FRC-USD',
                 'BREW-USD', 'ORARE-USD', 'AIRI-USD', 'FOUR-USD', 'OCT-USD', 'ZORA-USD', 'MAKI-USD', 'WORLD-USD',
                 'ZUM4826-USD', 'WSPP-USD', 'BXX-USD', 'CNN-USD', 'FOTA15067-USD', 'STX-USD', 'ZENI-USD', 'CRE8-USD',
                 'ETNA-USD', 'BITB-USD', 'MAX-USD', 'ADC-USD', 'VIPS-USD', 'QBT-USD', 'SET-USD', 'GSAIL-USD', 'SYP-USD',
                 'TRIO-USD', 'EDR-USD', 'NINO-USD', 'RENDOGE-USD', 'ZPT-USD', 'GPYX-USD', 'RISE-USD', 'FACE-USD',
                 'ACCEL-USD', 'EYE14996-USD', 'FEX-USD', 'IRD-USD', 'NYZO-USD', 'KNIGHT-USD', 'PRCY-USD', 'ACM-USD',
                 'BCUG-USD', 'BLUE-USD', 'DRC7420-USD', 'FTI-USD', 'PIPT-USD', 'BHO-USD', 'WG0-USD', 'ASKO-USD',
                 'CBM-USD', 'UGAS-USD', 'QUIN-USD', 'DRT-USD', 'BUZZ-USD', '1MT-USD', 'FBX18696-USD', 'NIX-USD',
                 'POSW-USD', 'SSTX-USD', 'LEAD-USD', 'ROUSH-USD', 'AC-USD', 'VISION18330-USD', 'BNU-USD', 'TCORE-USD',
                 'FDZ-USD', 'ELAND-USD', 'PGN-USD', 'IXT-USD', 'TRST-USD', 'GXT7310-USD', 'XCT-USD', 'PIRATE-USD',
                 'BID6857-USD', 'NTK-USD', 'RFI-USD', 'BITS-USD', 'NETKO-USD', 'BITG-USD', 'AOK-USD', 'HTZ-USD',
                 'VLXPAD-USD', 'OLXA-USD', 'JAR-USD', 'SOUL3501-USD', 'OSWAP-USD', 'PHR-USD', 'BRY-USD', 'GEM-USD',
                 'SHARE-USD', 'ZNT-USD', 'LEPA-USD', 'AID-USD', 'CHRP-USD', 'KEYFI-USD', 'RIO-USD', 'BOMB-USD',
                 'MNTP-USD', 'CLS-USD', 'GS-USD', 'BTA-USD', 'WTF12572-USD', 'PVT-USD', 'RENA-USD', 'MSR-USD',
                 'FLIXX-USD', 'TAP-USD', 'ADD-USD', 'POLIS-USD', 'ONG-USD', 'ZSC-USD', 'TOTM-USD', 'INEX-USD',
                 'NUX-USD', 'PAD11590-USD', 'ROCKI-USD', 'NSURE-USD', 'TIK-USD', 'MPAY-USD', 'BCV-USD', 'ZER-USD',
                 'PASC-USD', 'MOTA-USD', 'SNOB-USD', 'BSTY-USD', 'YIELD-USD', 'TUBE-USD', 'XCN-USD', 'ELAMA-USD',
                 'DOPE-USD', 'MODX-USD', 'CPO-USD', 'ALN-USD', 'ENG-USD', 'STAR-USD', 'STBU-USD', 'PUPPY17191-USD',
                 'CNTM-USD', 'DONUT-USD', 'WFX-USD', 'OGO-USD', 'SWING-USD', 'EXP-USD', 'FIC-USD', 'WQT-USD', 'CDL-USD',
                 'OKS-USD', 'INFI-USD', 'NAME-USD', 'PWR-USD', 'TSX-USD', 'FS-USD', 'NRP-USD', 'TNC-USD', 'COT-USD',
                 'XBP-USD', 'ARGON-USD', 'ETGP-USD', 'PYRO-USD', 'DVD-USD', 'SUB11932-USD', 'IND-USD', 'UFARM-USD',
                 'DONU-USD', 'TSL-USD', 'MYRA-USD', 'LAND-USD', 'YEE-USD', 'GENESIS-USD', 'TROLL-USD', 'GRFT-USD',
                 'HSC-USD', 'CTT9503-USD', 'DOKI-USD', 'BYN-USD', 'IFT-USD', 'LDFI-USD', 'KOBO-USD', 'BTR-USD',
                 'CORGIB-USD', 'FOR9510-USD', 'NDX-USD', 'MONK-USD', 'HAVY-USD', '1EARTH-USD', 'MICRO-USD',
                 'YF-DAI-USD', 'EGEM-USD', 'SAMU-USD', 'PLURA-USD', 'KDG-USD', 'TAG-USD', 'STEP-USD', '2GIVE-USD',
                 'NOR-USD', 'CTL-USD', 'DRC-USD', 'COLL-USD', 'ARQ-USD', 'DOM-USD', 'WOW8605-USD', 'DLT-USD', 'PLA-USD',
                 'XNV-USD', 'RAGE-USD', 'EOST-USD', 'MILK2-USD', 'NBX-USD', 'PEG-USD', 'NBC-USD', 'EBA-USD', 'ARCO-USD',
                 'AUC-USD', 'KUV-USD', 'BERRY-USD', 'JADE-USD', 'CYMT-USD', 'AMN-USD', 'CTRT-USD', 'MMO-USD',
                 'SHAKE-USD', 'VOX-USD', 'GOLD8281-USD', 'SENC-USD', 'MOMA-USD', 'ORAO-USD', 'DDK-USD', 'ESH-USD',
                 'XWP-USD', 'ION-USD', 'VDR-USD', 'EVY-USD', 'FOC-USD', 'KFX-USD', 'MX13696-USD', 'MTLX-USD', 'CUR-USD',
                 'LITHO-USD', 'KIMCHI-USD', 'VIVID-USD', 'FREED-USD', 'DINGO-USD', 'MAS-USD', 'DFSG-USD', 'HTD-USD',
                 'COB-USD', 'SKYRIM-USD', 'RGP-USD', 'CNS-USD', 'CJ-USD', 'RBIES-USD', 'BALPHA-USD', 'AMA-USD',
                 'N8V-USD', 'XAS-USD', 'AZUKI-USD', 'MIB-USD', 'LTHN-USD', 'L2-USD', '2KEY-USD', 'AXIS-USD', 'TRTT-USD',
                 'ZNZ-USD', 'SHDW-USD', 'NIFT-USD', 'NFY-USD', 'CHEESE-USD', 'KNDC-USD', 'MOJO-USD', 'NFXC-USD',
                 'MES-USD', 'TOTO-USD', 'SSP-USD', 'IQ3273-USD', 'ENT-USD', 'BUNI-USD', 'XSH-USD', 'EKT-USD',
                 'FONT-USD', 'GUM-USD', 'LUX-USD', 'LMY-USD', 'BC-USD', 'YVS-USD', 'CRACE-USD', 'AWSB-USD', 'PIPL-USD',
                 'JET-USD', 'RITO-USD', 'ZEBI-USD', 'YTN-USD', 'PKT-USD', 'TZC-USD', 'SIG-USD', 'SHIELD-USD',
                 'XDOGE14840-USD', 'CATT-USD', 'PRARE-USD', 'EXCL-USD', 'PHT5214-USD', 'POE-USD', 'SCONEX-USD',
                 'NAAL-USD', 'HEROEGG-USD', 'UPX-USD', 'SMTY-USD', 'PHT-USD', 'PKG-USD', 'BDP-USD', 'DOGES-USD',
                 'ZET-USD', 'INX-USD', 'SACT-USD', 'RBT10822-USD', 'XGT-USD', 'IG-USD', 'PYM-USD', 'MBC-USD',
                 'PLAT-USD', 'ROAD-USD', 'AUX-USD', 'VEKTOR-USD', 'SHOE-USD', 'OXB-USD', 'LYRA-USD', 'WARP-USD',
                 'BBS-USD', 'TANGO-USD', 'ARGO-USD', 'SFUEL-USD', 'CLX-USD', 'EGG8449-USD', 'LUN-USD', 'IOEN-USD',
                 'ATMOS-USD', 'DCNTR-USD', 'PAYB-USD', 'MBN-USD', 'PTD-USD', 'INSN-USD', 'DGC-USD', 'GBX-USD',
                 'BTZC-USD', 'SNRG-USD', 'MCC-USD', 'EVIL-USD', 'SNN-USD', 'VIKKY-USD', 'ITL-USD', 'NASH-USD',
                 'ZCR-USD', 'DYT-USD', 'AMM-USD', 'LIT-USD', 'PHX11727-USD', 'ICR-USD', 'DATP-USD', 'NTRN-USD',
                 'BBK-USD', 'MORE-USD', 'PEOS-USD', 'FTXT-USD', 'AFEN-USD', 'CHI5709-USD', 'ADI-USD', 'DVC-USD',
                 'UBN-USD', 'ASAFE-USD', 'AREPA-USD', 'BOLI-USD', 'SVX-USD', 'CBIX-USD', 'BUNNY-USD', 'AXE-USD',
                 'GFX-USD', 'NVC-USD', 'TCS-USD', 'QUAI-USD', 'EKO-USD', 'DMST-USD', 'RBT-USD', 'OPAL-USD', 'MEL-USD',
                 'SKIN-USD', 'ART-USD', 'DTRC-USD', 'CREDIT-USD', 'BTW-USD', 'DBET-USD', '1UP-USD', 'UP-USD', 'SCL-USD',
                 'KOI-USD', 'FXT-USD', 'ERO-USD', 'KURT-USD', 'BEET-USD', 'STEEP-USD', 'ROAD9145-USD', 'PRIX-USD',
                 'ZUKI-USD', 'LMT-USD', 'TYPH-USD', 'SXUT-USD', 'ANC-USD', 'KWT-USD', 'CORX-USD', 'VOLT-USD',
                 'MOWA-USD', 'ATB-USD', 'CSPN-USD', 'ENTS-USD', 'YOC-USD', 'CREO-USD', 'WSPP13119-USD', 'DEM-USD',
                 'EVC-USD', 'ITC-USD', 'RPZX-USD', 'ISA-USD', 'NTR-USD', 'TAN-USD', 'VAL7876-USD', 'NUTS-USD',
                 'ALP-USD', 'MEC-USD', 'YSEC-USD', 'QRT-USD', 'WCC-USD', 'UNIFY-USD', 'TNS-USD', 'KOMBAT-USD',
                 'FBN-USD', 'ELY-USD', 'COSM-USD', 'APC-USD', 'BNF-USD', 'CTT-USD', 'NEVA-USD', '2LC-USD',
                 'XDNA7262-USD', 'XPA-USD', 'TDP-USD', 'ARAW-USD', 'RASKO-USD', 'BURN-USD', 'BITC-USD', 'CALL-USD',
                 'WRC-USD', 'KWS-USD', 'EXE-USD', 'AIX-USD', 'FLOT-USD', 'ISLE-USD', 'TWIN-USD', 'GCN-USD', 'KFT-USD',
                 'XPTX-USD', 'VIDZ-USD', 'GB-USD', 'MYB-USD', 'IPL-USD', '1MIL-USD', 'XRA-USD', 'DAY-USD',
                 'ELTCOIN-USD', 'FUZZ-USD', 'MEDIC-USD', 'ARO-USD', 'HERO11067-USD', 'ALPHR-USD', 'DGTX-USD',
                 'SINS-USD', 'EUC-USD', 'UNIT-USD', 'BDS-USD', 'DEP9164-USD', 'INN-USD', 'CCN-USD', 'DDL-USD',
                 'SPK-USD', 'ONX-USD', 'ICOB-USD', 'GCR-USD', 'ACA13626-USD', 'ARCT-USD', 'NSD-USD', 'ECO-USD',
                 'CHART-USD', 'GCC-USD', 'HERON-USD', 'MAY-USD', 'ADZ-USD', 'ZUM-USD', 'VOTE-USD', 'PRX-USD', 'XPY-USD',
                 'AKA-USD', 'POST-USD', 'XBTC21-USD', 'TBX-USD', 'SPD-USD', 'ZPR-USD', 'GLT-USD', 'DSR-USD', 'BIT-USD',
                 'START-USD', 'ETHPLO-USD', 'BSD-USD', 'KSEED-USD', 'KALA-USD', 'SHMN-USD', 'MXX-USD', 'PEX-USD',
                 'OMC-USD', 'GSR-USD', 'C2-USD', 'LUS-USD', 'CNT-USD', 'HERB-USD', 'BEM-USD', 'FGC-USD', 'TCAT-USD',
                 'RBT9690-USD', 'BECN-USD', 'RVT-USD', 'EVN-USD', 'BERN-USD', 'BLTG-USD', 'FRST-USD', 'IC-USD',
                 'ZEUS-USD', 'GRIMM-USD', 'NAVY-USD', 'BBKFI-USD', 'MST-USD', 'REW-USD', 'ESCE-USD', 'ABX-USD',
                 'BOUTS-USD', 'DCTO-USD', 'XPT-USD', 'BXC5168-USD', 'BLOC-USD', 'GOSS-USD', 'VAULT-USD', 'BSL-USD',
                 'INNBC-USD', 'BTAD-USD', 'RUP-USD', 'GAJ-USD', 'EDRC-USD', 'BSC-USD', 'KNT-USD', 'DJV-USD', 'TAJ-USD',
                 'ORMEUS-USD', 'ELET-USD', 'SHVR-USD', 'KWIK-USD', 'KKO-USD', 'CIV-USD', 'XBI-USD', 'XDNA-USD',
                 'SCS-USD', 'IMG-USD', 'AMS-USD', 'HOR-USD', 'BELA-USD', 'YLC-USD', 'NPLC-USD', 'CSTL-USD', 'STAC-USD',
                 'KIND-USD', 'CCO-USD', 'GRO-USD', '3DC-USD', 'PNX-USD', 'EVT-USD', 'PKB-USD', 'TM2-USD', 'BELLY-USD',
                 'XGM-USD', 'ACOIN-USD', 'TIX-USD', 'XUEZ-USD', 'QUAN-USD', 'AIM-USD', 'DTC-USD', 'SCRIV-USD',
                 'FNX-USD', 'ALLOY-USD', 'KUN-USD', 'XGS-USD', 'FUZE-USD', 'GENE-USD', 'ELD-USD', 'XCO-USD', 'DLC-USD',
                 'CREVA-USD', 'SFCP-USD', 'TCH-USD', 'DFT-USD', 'CF-USD', 'DRM-USD', 'BON-USD', 'CRM-USD', 'SONG-USD',
                 'SFG-USD', 'KEMA-USD', 'COAL-USD', 'PYN-USD', 'ZYD-USD', 'GMC-USD', 'LTCR-USD', 'IBTC-USD', 'HOMI-USD',
                 'PYRK-USD', 'XOV-USD', 'HB-USD', 'JS-USD', 'STREAM-USD', 'IMS-USD', 'DAM-USD', 'MXT-USD', 'ALLBI-USD',
                 'ZINC-USD', 'LCMS-USD', 'TVNT-USD', 'SPR-USD', 'VLT-USD', 'MAC-USD', 'RIGEL-USD', 'PXI-USD', 'SHB-USD',
                 'ARB-USD', 'UNI-USD', 'DYNMT-USD', 'GPKR-USD', 'CAB-USD', 'PAYX-USD', 'QBC-USD', 'LTK-USD', 'VTX-USD',
                 'MARTK-USD', 'VEC2-USD', 'NOTE-USD', 'SEFA-USD', 'ARION-USD', 'PLNC-USD', 'LCP-USD', 'EGG7665-USD',
                 'SWC-USD', 'SCAP-USD', 'INFS-USD', 'DASHG-USD', 'CARE-USD', 'MERI-USD', 'HELP-USD', 'HVCO-USD',
                 'XAP-USD', 'BMXX-USD', 'JOINT-USD', 'CMT-USD', 'EXO-USD', 'CRDT-USD', 'IBANK-USD', 'MCPC-USD',
                 'GDR-USD', 'ROFI-USD', 'CBIX-P-USD', 'KTS-USD', 'ENTRC-USD', 'SOCC-USD', 'CNNC-USD', 'STAK-USD',
                 'ECU-USD', 'CXT-USD', 'LTCU-USD', 'HLIX-USD', 'WBB-USD', 'GXX-USD', 'ICON-USD', 'MATE-USD', 'VLS-USD',
                 'IUT-USD', 'CYL-USD', 'IBS-USD', 'SANDG-USD', 'KZC-USD', 'BLIZZ-USD', 'HELP4231-USD', 'CONX-USD',
                 'ARGUS-USD', 'PONZI-USD', 'IFX24-USD', 'FLL-USD', 'DIN-USD', 'HALV-USD', 'IRA-USD', 'ARNX-USD',
                 'STR-USD', 'STO-USD', 'BUL-USD', 'AAA-USD', 'TREX-USD', 'FAB-USD', 'NBXC-USD', 'NFT-USD', 'CPAN-USD',
                 'INNBCL-USD', 'YFFII-USD', 'RNBW-USD', 'MFTU-USD', 'SFK-USD', 'SBECOM-USD', 'SWIFT12658-USD',
                 'DBDOGE-USD', 'MOONWAY-USD', 'NTIC-USD', 'METAGIN-USD', 'ORI-USD', 'BEAR6934-USD', 'KRN-USD',
                 'AJE-USD', 'GMR-USD', 'LTN-USD', 'MBIRD-USD', 'CHIBA-USD', 'MEOW-USD', 'MANA12712-USD', 'BBK17151-USD',
                 'XPAY-USD', 'BIRB-USD', 'XECO-USD', 'FON-USD', 'PBLC-USD', 'MR-USD', 'DFSM-USD', 'CSD-USD', 'RBW-USD',
                 'IFC15672-USD', 'PLUS1-USD', 'FDLS-USD', 'ARMA-USD', 'DHX-USD', 'DSS-USD', 'RUSD-USD',
                 'BABYDOGE10970-USD', 'XHT-USD', 'META14705-USD', '7PXS-USD', 'ADOGE19567-USD', 'IXS-USD',
                 'IND19759-USD', 'JMPT-USD', 'NETT-USD', 'GLBD-USD', 'DEFIBULL-USD', 'VNDC-USD', 'MONS-USD',
                 'THECITADEL-USD', 'XGEM-USD', 'PRCH-USD', '3AIR-USD', 'GGTK-USD', 'CPHR-USD', 'SSU-USD', 'CPHR-USD',
                 'ARC13933-USD', 'DPAY21976-USD', 'SSU-USD', 'KOLNET-USD', 'MORE21339-USD', 'ACRE-USD', 'DRS-USD',
                 'TNDR21051-USD', 'WOOL-USD', 'DOGA-USD', 'KATS-USD', 'METAHOME-USD', 'UANG-USD', 'NEOM-USD',
                 'NOBF-USD', 'CANU-USD', 'WAULTX-USD', 'GER-USD', 'UCR-USD', 'DOG12078-USD', 'KAP-USD', 'ETHSHIB-USD',
                 'SUNNY-USD', 'MOONION-USD', 'TRU-USD', 'FROGEX-USD', 'CHARM-USD', 'BSC5725-USD', 'PLACE-USD',
                 'CGT8131-USD', 'EFT16230-USD', 'SHARO-USD', 'BEX-USD', 'TAP17718-USD', 'KINGDOG-USD', 'RTC18892-USD',
                 'OCTAGON-USD', 'POLYPAD-USD', 'TRK17835-USD', 'PURR-USD', 'SOLD-USD', 'CMIT-USD', 'SETH5765-USD',
                 'KTY-USD', 'GOTEM-USD', 'LNR22103-USD', 'GLD17489-USD', 'HUSKY-USD', 'ROY14928-USD', 'WCANTO-USD',
                 'CRC21560-USD', 'BOXCH-USD', 'NUBTC-USD', 'AFK20163-USD', 'SPW-USD', 'EAGON-USD', 'LTR-USD',
                 'LIFEBIRD-USD', 'METAMUSK-USD', 'METAZ-USD', 'FIT8499-USD', 'AVAI-USD', 'ECT11894-USD', 'ELT19238-USD',
                 'CATO14839-USD', 'GLAND-USD', 'SHIKA-USD', 'DOGEK-USD', 'ABC21696-USD', 'WTWOOL-USD', 'FWC-USD',
                 'NYM-USD', 'GMI17311-USD', 'DUSD18861-USD', 'ORE14997-USD', 'ASGARDV2-USD', 'TWOGE-USD', 'CRI-USD',
                 'HUB9086-USD', 'VSOL-USD', 'PLGR-USD', 'MOMO-USD', 'XEQ-USD', 'XVMC-USD', 'MINI-USD', 'OBX-USD',
                 'WANEOS-USD', 'TCOIN-USD', 'WBT-USD', 'NYT-USD', 'QUROZ-USD', 'INVEST-USD', 'SHOO-USD', 'LRPS-USD',
                 'DODB-USD', 'TOKENJENNY-USD', 'LINKETHRSI-USD', 'GMINES-USD', 'BEPR-USD', 'CHIK-USD', 'EVERSAFU-USD',
                 'CROC-USD', 'ENX-USD', 'MEDI17608-USD', 'RBS20415-USD', 'TIGER21063-USD', 'BEE21514-USD', 'CTP-USD',
                 'WEI-USD', 'LYD-USD', 'TFC9872-USD', 'MTB19299-USD', 'CROWN-USD', 'BITT-USD', 'SPRITZMOON-USD',
                 'GM17454-USD', 'UNDEAD19903-USD', 'WKIT-USD', 'TGNB-USD', 'AINU-USD', 'MAFA-USD', 'MARA-USD',
                 'AKTA-USD', 'MONO-USD', 'EURE-USD', 'LEMN-USD', 'MOSHI-USD', 'PULI-USD', 'VRBLOCKS-USD', 'IBVOL-USD',
                 'UDO15196-USD', 'VEGAS-USD', 'YCT-USD', 'FRN-USD', 'NTX-USD', 'EMB-USD', 'MASK20-USD', 'MMETA-USD',
                 'ELCASH-USD', 'BANK17642-USD', 'ETA-USD', 'KITTY13576-USD', 'UCM-USD', 'BABY21709-USD', 'BFG-USD',
                 'BVC-USD', 'ALTPAY-USD', 'KALI19622-USD', 'MUNCH-USD', 'YTZ-USD', 'GCAKE-USD', 'ARMOR-USD',
                 'REALM-USD', 'GOLC-USD', 'XTAL-USD', 'GREEN16649-USD', 'XRPAYNET-USD', 'STKE-USD', 'SLC16181-USD',
                 'SOUND-USD', 'RIDGE-USD', 'CSM20361-USD', 'LAEEB21670-USD', 'OSK-USD', 'BTNYX-USD', 'VST-USD',
                 'GIGA21493-USD', 'SVN-USD', 'PXP18192-USD', 'TNGBL-USD', 'JEJUDOGE-USD', 'DINOEGG-USD', 'XTRA-USD',
                 'NUDES-USD', 'LUNI15786-USD', 'TST21573-USD', 'FLS-USD', 'PACT16260-USD', 'IFT8949-USD',
                 'VST20192-USD', 'PAW17526-USD', 'QUA-USD', 'SAL-USD', 'INAZ-USD', 'NBR-USD', 'CBET-USD', 'HOOF-USD',
                 'IBG-USD', 'BBFT-USD', 'NFTZ-USD', 'YUSE-USD', 'THIS-USD', 'XWAP-USD', 'FEED-USD', 'BP-USD',
                 'BPT19542-USD', 'MVG-USD', 'FIRE16889-USD', 'SUPER19331-USD', 'ADACASH-USD', 'HXRO-USD', 'FTML-USD',
                 'SAFEEARTH-USD', 'SOLA-USD', 'METAV-USD', 'SATOZ-USD', 'MOON20639-USD', 'FREEMOON18485-USD',
                 'POINT21848-USD', 'CUSD21871-USD', 'MFI-USD', 'PEE-USD', 'MONO18853-USD', 'TOR18105-USD',
                 'CVC18362-USD', 'BTCMT-USD', 'GUT21618-USD', 'TFS-USD', 'BED-USD', 'CAI21726-USD', 'THALES-USD',
                 'JWL-USD', 'BITSU-USD', 'TGDAO-USD', 'MNODE-USD', 'PNT19816-USD', 'LFI-USD', 'GOGO15652-USD',
                 'ANON17100-USD', 'STSOL-USD', 'TETHYS-USD', 'PCR-USD', 'KUY-USD', 'OLYMPUS-USD', 'YUMMY-USD',
                 'BTFA-USD', 'KYCC-USD', 'PS1-USD', 'GRAP-USD', 'SAFEMARS-USD', 'DBAY-USD', 'HIPUNKS-USD', 'LOC-USD',
                 'CARGO-USD', 'LARIX-USD', 'DUSD12366-USD', 'ARTE18070-USD', 'AMH-USD', 'LTRBT-USD', 'EARNX18685-USD',
                 'OWL21047-USD', 'STIMA-USD', 'JUST-USD', 'CART-USD', 'NFTT-USD', 'GAR-USD', 'ALTBULL-USD',
                 'EDEN13512-USD', 'SOUL13342-USD', 'AKTIO-USD', 'MIX21528-USD', 'EUL-USD', 'UTO-USD', 'EFFORT-USD',
                 'VARC-USD', 'PIFI-USD', 'AENJ-USD', 'MELT-USD', 'KODX-USD', 'POKT-USD', 'VPND-USD', 'BAFC-USD',
                 'KEES-USD', 'SEN-USD', 'UBSN-USD', 'MYT-USD', 'COWS-USD', 'SFTMX-USD', 'CORGI-USD', 'ODEX-USD',
                 'BABYBITC-USD', 'DIGIS-USD', 'SAFUYIELD-USD', 'ULT5330-USD', 'IP3-USD', 'LUNAT-USD', 'YEL-USD',
                 'OCP-USD', 'PEM-USD', 'SCROOGE-USD', 'AFU-USD', 'USDS17285-USD', 'SERUM-USD', 'BC21-USD', 'HUAHUA-USD',
                 'SYL21511-USD', 'GRO12254-USD', 'GTX20892-USD', 'LION-USD', 'GGG-USD', 'PARAS-USD', 'MCT20906-USD',
                 'GFN-USD', 'NEOFI-USD', 'LFT19232-USD', 'NOVA12059-USD', 'YFX-USD', 'MLR-USD', 'RNO-USD', 'XJEWEL-USD',
                 'CONDOMS-USD', 'NST16807-USD', 'JOL-USD', 'ETHDOWN-USD', 'META15404-USD', 'YODE-USD', 'MARU-USD',
                 'HOKK-USD', 'FRED-USD', 'LEMC-USD', 'SHIBABNB-USD', 'SIE-USD', 'PRUF-USD', 'SUPERSQUID-USD',
                 'CALI-USD', 'CFXT-USD', 'THOR-USD', 'COAL6248-USD', 'SOLCASH-USD', 'MJT-USD', 'ENV12834-USD',
                 'MTD21418-USD', 'WINEREBRANDING-USD', 'VER-USD', 'MARSINU-USD', 'WAI-USD', 'CPD-USD', 'PGX20952-USD',
                 'WOOF17190-USD', 'DAO1-USD', 'PET-USD', 'FOXGIRL-USD', 'BCX-USD', 'GXT-USD', 'VBSWAP-USD',
                 'EGGPLUS-USD', 'CZF-USD', 'STARLY-USD', 'GTX-USD', 'TGR-USD', 'MINER-USD', 'JFC-USD', 'LIBFX-USD',
                 'PKN-USD', 'PIRATE10922-USD', 'HEROS-USD', 'JK-USD', 'SOWL-USD', 'BABYTIGER-USD', 'GOBTC-USD',
                 'CYCLE19898-USD', 'BLUES-USD', 'AUSD20411-USD', 'KSC13545-USD', 'ROAR17566-USD', 'COC14292-USD',
                 'MIMO10831-USD', 'LOFI20492-USD', 'EFB-USD', 'PWR16779-USD', 'ABR-USD', 'BLS-USD', 'GNP-USD',
                 'SHINJA-USD', 'BIGETH-USD', 'RODEO-USD', 'UMI12737-USD', 'CZBOMB-USD', 'FORTUNE-USD', 'SOCCER-USD',
                 'BBETH-USD', 'ZED-USD', 'KRIPTO-USD', 'UIM-USD', 'FWB-USD', 'VAT-USD', 'EWC-USD', 'POOCOIN-USD',
                 'GDR11699-USD', 'VTG-USD', 'WAS-USD', 'DOGBOSS-USD', 'GUILD-USD', 'LOCAL-USD', 'MWAR-USD', 'HODLX-USD',
                 'CLIST-USD', 'OLINK-USD', 'BABYYOOSHI-USD', 'AVO-USD', 'BFIGHT-USD', 'MGT-USD', 'BABA7921-USD',
                 'LDX19412-USD', 'DAILY-USD', 'CORAL-USD', 'BTCR-USD', 'LBLOCK21416-USD', '808TA-USD', 'MF-USD',
                 'DASHD-USD', 'FILST-USD', 'EDUX-USD', 'BOBC-USD', 'ALPHA18300-USD', 'ANTIS-USD', 'WCFG-USD',
                 'ZILLIONXO-USD', 'SMARS-USD', 'DMSFT-USD', 'NTK3149-USD', 'BSHIB-USD', 'SAVEANIMAL-USD', 'METADAO-USD',
                 'TRXC-USD', 'PLS19964-USD', 'TRAVEL18597-USD', 'FIT20049-USD', 'HONOR-USD', 'INDEX-USD',
                 'CRUSADER-USD', 'NINKY-USD', 'F1C-USD', 'STFU-USD', 'ALTB-USD', 'WOLVERINU-USD', 'ARIX-USD',
                 'SMRT-USD', 'ISKY-USD', 'INVI-USD', 'RIDE-USD', 'SETH2-USD', 'SER-USD', 'MSHARE-USD', 'BME-USD',
                 'MKONG-USD', 'GKF-USD', 'META11373-USD', 'MMG18554-USD', 'DKUMA-USD', 'USHARE-USD', 'BABYFB-USD',
                 'BITANT-USD', 'ORI18234-USD', 'CHECKR-USD', 'DOSA-USD', 'MOVE-USD', 'PFTM-USD', 'TALK-USD',
                 'TALK15260-USD', 'EQ-USD', 'EARN-USD', 'ELEF-USD', 'KACY-USD', '5TABLE-USD', 'AWG-USD', 'BKR-USD',
                 'SHIBZ-USD', 'ZIP-USD', 'MMA18166-USD', 'OBX-USD', 'WANEOS-USD', 'TCOIN-USD', 'WBT-USD', 'NYT-USD',
                 'QUROZ-USD', 'INVEST-USD', 'SHOO-USD', 'LRPS-USD', 'DODB-USD', 'BEPR-USD', 'CZATS-USD', 'JOY19401-USD',
                 'ESC-USD', 'HATCHY-USD', 'ATPAY-USD', 'HON18025-USD', 'OSM-USD', 'ZEDXION-USD', 'MPH-USD', 'WALKN-USD',
                 'FCF-USD', 'NFTSTYLE-USD', 'MASH-USD', 'KAZOKU-USD', 'MOONLIGHT-USD', 'PETH-USD', 'MFAM-USD',
                 'DIKO-USD', 'RODEO-USD', 'UMI12737-USD', 'CZBOMB-USD', 'FORTUNE-USD', 'SOCCER-USD', 'BBETH-USD',
                 'ZED-USD', 'KRIPTO-USD', 'UIM-USD', 'FWB-USD', 'VAT-USD', 'EWC-USD', 'POOCOIN-USD', 'GDR11699-USD',
                 'VTG-USD', 'WAS-USD', 'DOGBOSS-USD', 'GUILD-USD', 'LOCAL-USD', 'MWAR-USD', 'HODLX-USD', 'CLIST-USD',
                 'OLINK-USD', 'BABYYOOSHI-USD', 'VODKA-USD', 'SANDWICH-USD', 'ZILLADOGE-USD', 'BR34P-USD', 'SFV2-USD',
                 'VERSE16580-USD', 'SPE18149-USD', 'SMURF-USD', 'CPR17545-USD', 'MEME18938-USD', 'DYT14357-USD',
                 'SAVAX-USD', 'XLS-USD', 'SPORTS-USD', 'HID-USD', 'WCRO-USD', 'DMZ-USD', 'WEB30-USD', 'HRTS-USD',
                 'SEAH-USD', 'NODL-USD', 'CFL365-USD', 'BSGG-USD', 'BPIT-USD', 'KRAC-USD', 'NODE4773-USD', 'MOLK-USD',
                 'BULL5157-USD', 'CVAG-USD', 'CAW-USD', 'HPY-USD', 'MBET17498-USD', 'HODL-USD', 'RUNE8272-USD',
                 'SPT18151-USD', 'SUKUNA-USD', 'EDC8212-USD', 'PALM-USD', 'BIXB-USD', 'BRCP-USD', 'ARCX-USD',
                 'NEON-USD', 'BITWALLET-USD', 'RTO-USD', 'MYTE-USD', 'NEMO-USD', 'JACY-USD', 'GRBT-USD',
                 'LOOT17623-USD', 'REU20526-USD', 'ZMT-USD', 'EULER-USD', 'SON15315-USD', 'AMPLE-USD', 'CITY18670-USD',
                 'MATRIX-USD', 'TIR-USD', 'CCY-USD', 'UNO20694-USD', 'SONNE-USD', 'SLOUGI-USD', 'QUA17084-USD',
                 'OSK20828-USD', 'VIRES-USD', 'RIP-USD', 'FIBO19221-USD', 'CHOICE-USD', 'MBF-USD', 'CREAL-USD',
                 'CMF18341-USD', 'AZERO-USD', 'MMA18166-USD', 'PINU20138-USD', 'RUN19638-USD', 'JET21888-USD',
                 'FEG-USD', 'BSGG-USD', 'BPIT-USD', 'KRAC-USD', 'NODE4773-USD', 'MOLK-USD', 'BULL5157-USD', 'CVAG-USD',
                 'SEAH-USD', 'NODL-USD', 'CFL365-USD', 'CAW-USD', 'HPY-USD', 'MBET17498-USD', 'HODL-USD',
                 'RUNE8272-USD', 'SPT18151-USD', 'SUKUNA-USD', 'EDC8212-USD', 'GXP-USD', 'SWIN-USD', '1GOLD-USD',
                 'WNYC-USD', 'CHEESE15565-USD', 'BABL-USD', 'JACK-USD', 'DVRS-USD', 'ALYA-USD', 'ARDN-USD', 'PIG-USD',
                 'RAM-USD', 'POOP21757-USD', 'KON-USD', 'LCDOT-USD', 'THB-USD', 'LABS21498-USD', 'JELLY-USD', 'WDC-USD',
                 'GMD-USD', 'QTA-USD', 'KIT-USD', 'POM-USD', 'CORGI13286-USD', 'FLASH13862-USD', 'TUT16505-USD',
                 'TRUBGR-USD', 'DMT19687-USD', 'CT22199-USD', 'SMTF-USD', 'EXZO-USD', 'BANK-USD', 'SDBY-USD',
                 'XSOL-USD', 'RBXSAMURAI-USD', 'LINKDOWN-USD', 'LINA-USD', 'ACES-USD', 'RDNT-USD', 'UNIX-USD',
                 'NBP-USD', 'DSG-USD', 'DIQ-USD', 'ADDY-USD', 'NOAH-USD', 'AQUA-USD', 'OGEM-USD', 'IFIT-USD',
                 'NORA-USD', 'ALGOPAD-USD', 'XRPDOWN-USD', 'WALL-USD', 'MARX-USD', 'KEKW-USD', 'RATS-USD', 'PEAR-USD',
                 'ILA-USD', 'XCM-USD', 'BRTR-USD', 'DXGM-USD', 'DHR-USD', 'BT-USD', 'SLCL-USD', 'LIST-USD', 'POPS-USD',
                 'REVO9391-USD', 'DVDX-USD', 'PALM-USD', 'SHIH-TZU-USD', 'XSPECTAR-USD', 'KRED-USD', 'SAFEICARUS-USD',
                 'ARCX-USD', 'NEON-USD', 'BITWALLET-USD', 'BIXB-USD', 'BRCP-USD', 'RTO-USD', 'MYTE-USD', 'NEMO-USD',
                 'JACY-USD', 'GRBT-USD', 'GSI-USD', 'CDR-USD', 'TWD-USD', 'YOLLLO-USD', 'BTCBR-USD', 'GOETH-USD',
                 'MVC15493-USD', 'BPLUS-USD', 'BVT-USD', 'SWERVE-USD', 'BIO-USD', 'KUB-USD', 'MOR-USD', 'MEMA17927-USD',
                 'MCF-USD', 'WIRTUAL-USD', 'HLD-USD', 'PETH17458-USD', 'SMOON15352-USD', 'PROUD-USD', 'VISION-USD',
                 'UFI-USD', 'SANINU-USD', 'TOC22019-USD', 'HUNNY-USD', 'DARK17118-USD', 'CWT10807-USD', 'AMB19556-USD',
                 'TDX-USD', 'BACON15410-USD', 'ADO-USD', 'SPA17626-USD', 'DUCK13322-USD', 'AUV-USD', 'STEAK-USD',
                 'CRX15069-USD', 'MAT20950-USD', 'ALM-USD', 'BEE20835-USD', 'ECOIN-USD', 'FRZSS-USD', 'KTO-USD',
                 'OUT-USD', 'AVO-USD', 'BFIGHT-USD', 'MGT-USD', 'BABA7921-USD', 'LDX19412-USD', 'DAILY-USD',
                 'CORAL-USD', 'BTCR-USD', 'LBLOCK21416-USD', '808TA-USD', 'MF-USD', 'DASHD-USD', 'FILST-USD',
                 'EDUX-USD', 'ANTIS-USD', 'WCFG-USD', 'BOBC-USD', 'ALPHA18300-USD', 'ZILLIONXO-USD', 'SMARS-USD',
                 'DMSFT-USD', 'NTK3149-USD', 'BSHIB-USD', 'SAVEANIMAL-USD', 'METADAO-USD', 'TRXC-USD', 'PLS19964-USD',
                 'TRAVEL18597-USD', 'FIT20049-USD', 'HONOR-USD', 'INDEX-USD', 'CRUSADER-USD', 'NINKY-USD', 'F1C-USD',
                 'STFU-USD', 'ALTB-USD', 'WOLVERINU-USD', 'ARIX-USD', 'SMRT-USD', 'ISKY-USD', 'INVI-USD', 'RIDE-USD',
                 'SETH2-USD', 'SER-USD', 'MSHARE-USD', 'BME-USD', 'MKONG-USD', 'GKF-USD', 'META11373-USD',
                 'MMG18554-USD', 'BITANT-USD', 'USHARE-USD', 'ORI18234-USD', 'CHECKR-USD', 'DOSA-USD', 'MOVE-USD',
                 'PFTM-USD', 'ALTBULL-USD', 'EDEN13512-USD', 'SOUL13342-USD', 'AKTIO-USD', 'MIX21528-USD', 'EUL-USD',
                 'UTO-USD', 'EFFORT-USD', 'VARC-USD', 'PIFI-USD', 'AENJ-USD', 'MELT-USD', 'KODX-USD', 'POKT-USD',
                 'VPND-USD', 'BAFC-USD', 'KEES-USD', 'SEN-USD', 'UBSN-USD', 'MYT-USD', 'COWS-USD', 'SFTMX-USD',
                 'CORGI-USD', 'ODEX-USD', 'BABYBITC-USD', 'DIGIS-USD', 'SAFUYIELD-USD', 'ULT5330-USD', 'IP3-USD',
                 'LUNAT-USD', 'YEL-USD', 'OCP-USD', 'PEM-USD', 'SCROOGE-USD', 'AFU-USD', 'USDS17285-USD', 'SERUM-USD',
                 'BC21-USD', 'HUAHUA-USD', 'SYL21511-USD', 'GRO12254-USD', 'GTX20892-USD', 'LION-USD', 'XGLI-USD',
                 'GNAR-USD', 'SBNK-USD', 'NEXM-USD', 'A2A-USD', 'C3-USD', 'IDK-USD', 'IONX-USD', 'PURE-USD', 'FUSD-USD',
                 'CHEX-USD', 'EMT-USD', 'FVP-USD', 'LETSGO-USD', 'BAS11279-USD', 'FMG-USD', 'PAVAX-USD', 'VIS-USD',
                 'OUSDC-USD', 'FENOMY-USD', 'CCP-USD', 'FEED17088-USD', 'VAL21419-USD', 'PIGGY-USD', 'BRO15748-USD',
                 'DOGDEFI-USD', 'RBX18634-USD', '3OH-USD', 'FLETA-USD', 'DOGEHEDGE-USD', 'VITA-USD', 'IBAT-USD',
                 'ONEPIECE-USD', 'HDRN-USD', 'ACSI-USD', 'BOX20357-USD', 'BEC-USD', 'WST-USD', 'FPFT-USD', 'BRRR-USD',
                 'DOC-USD', 'SOULO-USD', 'MHUB-USD', 'PINU-USD', 'ICSA-USD', 'UMBR-USD', 'DPT-USD', 'AXIN-USD',
                 'LINKBULL-USD', 'DEMY-USD', 'TRAT-USD', 'BYND-USD', 'SMASH-USD', 'CORIS-USD', 'DTUBE-USD', 'VITY-USD',
                 'SAFUU-USD', 'NKCLC-USD', 'ATP7814-USD', 'LCD-USD', 'LBLOCK-USD', 'CLS20416-USD', 'BEE20177-USD',
                 'ARTIC-USD', 'MST19267-USD', 'BNTY19468-USD', 'SDC19634-USD', 'BBL19379-USD', 'ADACASH-USD',
                 'HXRO-USD', 'FTML-USD', 'SAFEEARTH-USD', 'SOLA-USD', 'METAV-USD', 'SATOZ-USD', 'MOON20639-USD',
                 'FREEMOON18485-USD', 'POINT21848-USD', 'CUSD21871-USD', 'MFI-USD', 'PEE-USD', 'MONO18853-USD',
                 'TOR18105-USD', 'CVC18362-USD', 'BTCMT-USD', 'GUT21618-USD', 'TFS-USD', 'BED-USD', 'CAI21726-USD',
                 'THALES-USD', 'JWL-USD', 'BITSU-USD', 'TGDAO-USD', 'MNODE-USD', 'PNT19816-USD', 'LFI-USD',
                 'GOGO15652-USD', 'ANON17100-USD', 'STSOL-USD', 'TETHYS-USD', 'PCR-USD', 'KUY-USD', 'OLYMPUS-USD',
                 'YUMMY-USD', 'BTFA-USD', 'ETHHEDGE-USD', 'NEKOS-USD', 'GENX-USD', 'OXFI-USD', 'BX21331-USD',
                 'DEGN-USD', 'MV21697-USD', 'MOBX-USD', 'VADA-USD', 'DCY-USD', 'ST20434-USD', 'SURV-USD', 'CLUB-USD',
                 'POOP21436-USD', 'EVERF-USD', 'BUFFS-USD', 'CWD-USD', 'ARTI-USD', 'NODY-USD', 'METR-USD',
                 'DINGO16185-USD', 'CORN21906-USD', 'RES-USD', 'VIDYX-USD', 'KSH-USD', 'OCAVU-USD', 'DINO18731-USD',
                 'MST11817-USD', 'ASH-USD', 'FORT15742-USD', 'GIL17402-USD', 'RCG-USD', 'QIN-USD', 'SYL-USD',
                 'PARA12887-USD', 'DAWGS-USD', 'CSD-USD', 'IFC15672-USD', 'RBW-USD', 'PLUS1-USD', 'FROGEX-USD',
                 'TRU-USD', 'PLACE-USD', 'CSC-USD', 'PCI-USD', 'NT-USD', 'SAPP-USD', 'ALTER-USD', 'BCW-USD',
                 'SOLAPE-USD', 'NFTL12920-USD', 'BABYOKX-USD', 'WCSOV-USD', 'EXFI-USD', 'PAYZ-USD', 'MLOKY-USD',
                 'TRONPAD-USD', 'PITI-USD', 'MNDE-USD', 'WPKT-USD', 'AART-USD', 'GHSP-USD', 'WSYS-USD', 'AMAS-USD',
                 'WANSUSHI-USD', 'BZRX-USD', 'WIT-USD', 'SXC-USD', 'BKK-USD', 'PSY-USD', 'SCT16098-USD', 'MATATA-USD',
                 'FIA-USD', '2SHARES-USD', 'AKL-USD', 'BLS12693-USD', 'LOOP20998-USD', 'CATPAY-USD', 'POCROC-USD',
                 'MIDAS-USD', 'ANGEL15586-USD', 'LMG-USD', 'PAPEL-USD', 'SIERRA-USD', 'EARN17781-USD', 'KAIBA-USD',
                 'KOSON-USD', 'XANK-USD', 'UBIN-USD', 'BUCKY-USD', 'GENF-USD', 'ETHHEDGE-USD', 'NEKOS-USD', 'GENX-USD',
                 'OXFI-USD', 'BX21331-USD', 'DEGN-USD', 'MV21697-USD', 'MOBX-USD', 'VADA-USD', 'DCY-USD', 'ST20434-USD',
                 'SURV-USD', 'CLUB-USD', 'POOP21436-USD', 'EVERF-USD', 'BUFFS-USD', 'CWD-USD', 'NODY-USD', 'METR-USD',
                 'ARTI-USD', 'CIR-USD', 'DINGO16185-USD', 'CORN21906-USD', 'RES-USD', 'VIDYX-USD', 'KSH-USD',
                 'OCAVU-USD', 'DINO18731-USD', 'MST11817-USD', 'ASH-USD', 'FORT15742-USD', 'GIL17402-USD', 'RCG-USD',
                 'QIN-USD', 'SYL-USD', 'PARA12887-USD', 'DAWGS-USD', 'CSC-USD', 'PCI-USD', 'NT-USD', 'SAPP-USD',
                 'ALTER-USD', 'BCW-USD', 'SOLAPE-USD', 'NFTL12920-USD', 'BABYOKX-USD', 'MTRX20346-USD', 'ACM17791-USD',
                 'ZNT20903-USD', 'SLG-USD', 'PURR20771-USD', 'MVP14921-USD', 'HIPPO-USD', 'YT-USD', 'RUYI-USD',
                 'STN9043-USD', 'WHIVE-USD', 'SPKI-USD', 'SPEED-USD', 'METO-USD', 'ANFT-USD', 'EXFI-USD', 'PAYZ-USD',
                 'MLOKY-USD', 'TRONPAD-USD', 'PITI-USD', 'MNDE-USD', 'WPKT-USD', 'AART-USD', 'GHSP-USD', 'WSYS-USD',
                 'AMAS-USD', 'WANSUSHI-USD', 'BZRX-USD', 'WIT-USD', 'SXC-USD', 'BKK-USD', 'PSY-USD', 'SCT16098-USD',
                 'MATATA-USD', 'FIA-USD', '2SHARES-USD', 'AKL-USD', 'BLS12693-USD', 'LOOP20998-USD', 'CATPAY-USD',
                 'POCROC-USD', 'MIDAS-USD', 'ANGEL15586-USD', 'LMG-USD', 'PAPEL-USD', 'SIERRA-USD', 'EARN17781-USD',
                 'KAIBA-USD', 'KOSON-USD', 'XANK-USD', 'UBIN-USD', 'BUCKY-USD', 'GENF-USD', 'ETHHEDGE-USD', 'NEKOS-USD',
                 'GENX-USD', 'OXFI-USD', 'BX21331-USD', 'DEGN-USD', 'MV21697-USD', 'MOBX-USD', 'VADA-USD', 'DCY-USD',
                 'ST20434-USD', 'SURV-USD', 'CLUB-USD', 'POOP21436-USD', 'EVERF-USD', 'BUFFS-USD', 'CWD-USD',
                 'ARTI-USD', 'NODY-USD', 'METR-USD', 'CIR-USD', 'DINGO16185-USD', 'CORN21906-USD', 'RES-USD',
                 'VIDYX-USD', 'KSH-USD', 'OCAVU-USD', 'DINO18731-USD', 'MST11817-USD', 'ASH-USD', 'FORT15742-USD',
                 'GIL17402-USD', 'RCG-USD', 'QIN-USD', 'SYL-USD', 'PARA12887-USD', 'DAWGS-USD', 'CSC-USD', 'PCI-USD',
                 'NT-USD', 'SAPP-USD', 'ALTER-USD', 'BCW-USD', 'SOLAPE-USD', 'NFTL12920-USD', 'BABYOKX-USD',
                 'BONFIRE-USD', 'CSD-USD', 'IFC15672-USD', 'RBW-USD', 'PLUS1-USD', 'FROGEX-USD', 'TRU-USD', 'PLACE-USD',
                 'FDLS-USD', 'ARMA-USD', 'DOGA-USD', 'DHX-USD', 'DSS-USD', 'RUSD-USD', 'BABYDOGE10970-USD',
                 'METAHOME-USD', 'XRA3234-USD', 'GCAKE-USD', 'LEAG-USD', 'CHIK-USD', 'MHAM-USD', 'WEI-USD',
                 'KITTY13576-USD', 'UCM-USD', 'ALTPAY-USD', 'BABY21709-USD', 'OSK-USD', 'LYD-USD', 'BVC-USD', 'YTZ-USD',
                 'KALI19622-USD', 'MUNCH-USD', 'BFG-USD', 'IBVOL-USD', 'FRN-USD', 'VEGAS-USD', 'YCT-USD', 'MMETA-USD',
                 'MASK20-USD', 'ETA-USD', 'ARMOR-USD', 'SLC16181-USD', 'TNGBL-USD', 'DINOEGG-USD', 'SOUND-USD',
                 'REALM-USD', 'XTRA-USD', 'NUDES-USD', 'STKE-USD', 'GREEN16649-USD', 'JEJUDOGE-USD', 'TRACE-USD',
                 '50X-USD', 'DRGNZ-USD', 'SHR18009-USD', 'FLASH16978-USD', 'LUNI15786-USD', 'IFT8949-USD',
                 'WINU16575-USD', 'CPC9091-USD', 'TAP12702-USD', 'SPRING-USD', 'CTL15730-USD', 'BRT20263-USD',
                 'ORC7103-USD', 'XSP-USD', 'LUSD17225-USD', 'KFI20782-USD', 'MAI-USD', 'APD-USD', 'PACT16260-USD',
                 'VST20192-USD', 'PAW17526-USD', 'ETHK-USD', 'SCRL-USD', 'BNBH-USD', 'NOIZ-USD', 'ZPAE-USD', 'SAL-USD',
                 'INAZ-USD', 'BBFT-USD', 'WBDC-USD', 'SDC-USD', 'MOONPIRATE-USD', 'DEVO-USD', 'IDYP-USD', 'DCY-USD',
                 'IBG-USD', 'NBR-USD', 'NFTZ-USD', 'HOOF-USD', 'YUSE-USD', 'XWAP-USD', 'GIVING-USD', 'CBET-USD',
                 'THIS-USD', 'FEED-USD', 'BP-USD', 'CSM20361-USD', 'LAEEB21670-USD', 'HEDGE-USD', 'MEGALAND-USD',
                 'BPT19542-USD', 'VST-USD', 'RIDGE-USD', 'BTNYX-USD', 'GIGA21493-USD', 'SVN-USD', 'PXP18192-USD',
                 'HIPPO-USD', 'WVET-USD', 'WHIVE-USD', 'YT-USD', 'SPKI-USD', 'METO-USD', 'ANFT-USD', 'CREDI-USD',
                 'SPRITZMOON-USD', 'POCO-USD', 'SB17448-USD', 'UNIS-USD', 'BIOS-USD', 'WARS-USD', 'NEWTON-USD',
                 'KCAKE-USD', 'KITTY-USD', 'BET21869-USD', 'MELON-USD', 'RFG-USD', 'REAU-USD', 'MARA-USD',
                 'CREDIT6668-USD', 'SOLIDSEX-USD', 'HFI-USD', 'FER-USD', 'AQUARI-USD', 'AQS-USD', 'LSHARE-USD',
                 'WOW19552-USD', 'CDONK-USD', 'EVERETH-USD', 'MEAD-USD', 'ATEM-USD', 'WNZ-USD', 'CHH-USD', 'UWU-USD',
                 'HZM-USD', 'HNY-USD', 'MAD19281-USD', 'TBC21829-USD', 'GVR-USD', 'LCR-USD', 'SONAR-USD',
                 'YAY11664-USD', 'LOOT15890-USD', 'MLB-USD', 'XGRAPE-USD', 'SUNEKU-USD', 'RLM-USD', 'FIRE16889-USD',
                 'PURR20771-USD', 'SLG-USD', 'AUR-USD', 'ZNT20903-USD', 'XRX-USD', 'GOV-USD', 'MVG-USD', 'MVP14921-USD',
                 'SUPER19331-USD', 'ACM17791-USD', 'DELFI-USD', 'IMBTC-USD', 'WBIND-USD', 'KISHIBURNO-USD', 'TOPG-USD',
                 'KISHUTAMA-USD', 'HOGL-USD', 'CTFT-USD', 'GREEN-USD', 'GNL-USD', 'POWER-USD', 'VIRAL-USD', 'ROCKY-USD',
                 'GRT22086-USD', 'LOGE-USD', 'BABYSHIB-USD', 'TRND-USD', 'H2O21637-USD', 'SWAPP-USD', 'CHS-USD',
                 'FLOVM-USD', 'INSTINCT-USD', 'MLT16557-USD', 'BEAGLE-USD', 'TIME11585-USD', 'CHEEZ-USD', 'PES-USD',
                 'BITCOIN-USD', 'SHIBA22-USD', 'BULLSHIT-USD', 'SADA-USD', 'GREENBIOX-USD', 'MEPAD-USD', 'MMS-USD',
                 'SOG-USD', 'CGO-USD', 'BEACH21739-USD', 'UEC-USD', 'SAO19631-USD', 'QTF-USD', 'CZBUSD-USD',
                 'TDROP-USD', 'LKN14313-USD', 'WOLF19995-USD', 'ASIMI-USD', 'WLD20756-USD', 'CNT19611-USD',
                 'CHAIN21728-USD', 'TRISM-USD', 'XOT-USD', 'FAN10609-USD', 'MDL-USD', 'FORS18196-USD', 'MIY-USD',
                 'BLITZ-USD', 'GES-USD', 'SKRT-USD', 'QANX-USD', 'TATA-USD', 'YUKI-USD', 'UM16090-USD', 'FLURRY-USD',
                 'XQC-USD', 'PROPEL-USD', 'AUN-USD', 'XFUND-USD', 'MINECRAFT-USD', 'CANDYLAD-USD', 'JT-USD', 'KDC-USD',
                 'FXT21784-USD', 'SNE-USD', 'MAINST-USD', 'MGCHI-USD', 'CPX21950-USD', 'KODI18024-USD', 'HCT14509-USD',
                 'MIMO15477-USD', 'OLAND-USD', 'YOU15115-USD', 'BOT16262-USD', 'RDL-USD', 'MINE19533-USD',
                 'LOF17696-USD', 'TSY-USD', 'CHRO-USD', 'GAT-USD', 'MINIBTC-USD', 'SHF22094-USD', 'SKELETON-USD',
                 'ITUBE-USD', 'VEN21171-USD', 'UMAMI-USD', 'PPC6253-USD', 'PTX19210-USD', 'DOGEBNB-USD', 'BEMD-USD',
                 'BITO-USD', 'DIG-USD', 'MOOO-USD', 'SFM-USD', 'WMX-USD', 'MOON7396-USD', 'BLKS-USD', 'DEK-USD',
                 'YARD-USD', 'LOUD-USD', 'ENNO-USD', 'RARE-USD', 'BIMP-USD', 'NXTT-USD', 'CLCT-USD', 'DAIN-USD',
                 'MCOS-USD', 'CMLT-USD', 'ETHPY-USD', 'PODO-USD', 'BABYDOGECASH-USD', 'ZODI-USD', 'ZINA-USD', 'DMC-USD',
                 'HDFL-USD', 'CPSP-USD', 'DFD-USD', 'SWAG-USD', 'WENTXN-USD', 'AFIN-USD', 'TOON-USD', 'COGE-USD',
                 'DVOO-USD', 'WOLF-USD', 'MARS-USD', 'ETH2X-FLI-USD', 'ATLAS21593-USD', 'STREETH-USD', 'SHINO-USD',
                 'WBX-USD', 'HER-USD', 'NUME-USD', 'QUID-USD', 'CAKESWAP-USD', 'AT17891-USD', 'XCB-USD', 'STARLNK-USD',
                 'SLEEP-USD', 'LSWAP-USD', 'MNFT-USD', 'MEFI-USD', 'CRYY-USD', 'ZLDA-USD', 'ADAM-USD', 'MGOD-USD',
                 'XZAR-USD', 'NBG-USD', 'INUS-USD', 'BMCC-USD', 'DSFR-USD', 'ROAO-USD', 'RIPH-USD', 'NTRC-USD',
                 'DICE6501-USD', 'APLUS-USD', 'ORE12743-USD', 'JUR-USD', 'MDO19678-USD', 'BCA7619-USD', '37C-USD',
                 'AKREP-USD', 'JADE14938-USD', 'SANJI-USD', 'TKB-USD', 'QRX-USD', 'BONE20809-USD', 'XALGO-USD',
                 'KITTY14382-USD', 'SWP20973-USD', 'LUNAPAD-USD', 'WITCH-USD', 'RBO-USD', 'FUNDX-USD', 'GGTKN-USD',
                 'MIDBULL-USD', 'TBE-USD', 'ARTII-USD', 'FOL-USD', 'BFT21952-USD', 'PLG-USD', 'GENI-USD', 'LEOPARD-USD',
                 'HIDOODLES-USD', 'ST-USD', 'KLKS-USD', 'UXD-USD', 'HUM19625-USD', 'SPANK-USD', 'GBD-USD',
                 'FORGE19976-USD', 'FPC-USD', 'AKC-USD', 'MNZ-USD', 'BDC-USD', 'CBP-USD', 'QUA15857-USD',
                 'DICK14067-USD', 'EGS-USD', 'WEGLD-USD', 'SAFU17455-USD', 'BTCPX-USD', 'WWDOGE-USD', 'ROF-USD',
                 'HAREC-USD', 'FLIBERO-USD', 'NIROS-USD', 'DOGEFOOD-USD', 'STA6867-USD', 'ETH20-USD', 'VISA-USD',
                 'ECC15684-USD', 'SAUCE-USD', 'UUSD-USD', 'XRP-BF2-USD', 'DPIX-USD', 'OLIVE-USD', 'PIN17109-USD',
                 'METAD-USD', 'SV-USD', 'BACON-USD', 'MFI20838-USD', 'CATS18388-USD', 'TAX-USD', '1AMD-USD',
                 'MDB20408-USD', 'MBP-USD', 'MBD-USD', 'XTK-USD', 'FBS-USD', 'AMPT18729-USD', 'TOYO-USD', 'NMX-USD',
                 'SPDX-USD', 'GYSR-USD', 'NPC-USD', 'DSLV-USD', 'CEJI-USD', 'POWA-USD', 'YVAULTLP-YCURVEYYCRV-USD',
                 'DUKE-USD', 'SHKI-USD', 'RUN-USD', 'SDLN-USD', 'COMT-USD', 'DFM-USD', 'EVRT-USD', 'POLP-USD',
                 'MOOX-USD', 'TRIVIA-USD', 'SHINTAMA-USD', 'INES-USD', 'BOTZ-USD', 'MYNE-USD', 'CNDL-USD', 'POMI-USD',
                 'SDL-USD', 'XFI-USD', 'METAWAR-USD', 'SHIBA22-USD', 'BULLSHIT-USD', 'ABIC-USD', 'SADA-USD',
                 'GREENBIOX-USD', 'GOAT16050-USD', 'MIMAS-USD', 'XIL-USD', 'MEPAD-USD', 'MMS-USD', 'SOG-USD', 'CGO-USD',
                 'BEACH21739-USD', 'UEC-USD', 'SAO19631-USD', 'QTF-USD', 'NUARS-USD', 'ACT11706-USD', 'CZBUSD-USD',
                 'TDROP-USD', 'LKN14313-USD', 'WOLF19995-USD', 'ASIMI-USD', 'WLD20756-USD', 'TITANO-USD', 'FUTURE-USD',
                 'FNC-USD', 'ALRIHLA-USD', 'ORC16880-USD', 'KEANU-USD', 'CPU8295-USD', 'FFN-USD', 'TAC13743-USD',
                 'SHAMAN-USD', 'SSS12431-USD', 'TOI-USD', 'CHES-USD', 'GENS-USD', 'STELLARINU-USD', 'BILI7930-USD',
                 'ISLAMI-USD', 'PINT-USD', 'SAFEMONEY-USD', 'BASED-USD', 'FITT-USD', 'TART-USD', 'MPLX-USD', 'SHAK-USD',
                 'CASH-USD', 'HAKA-USD', '777-USD', 'OURS-USD', 'ZGD-USD', 'FYN-USD', 'LOV-USD', 'LOOP18761-USD',
                 'GAM-USD', 'BABY14253-USD', 'BTCDOWN-USD', 'OBROK-USD', 'PET16333-USD', 'BMN-USD', 'USDTE-USD',
                 'WALLPHY-USD', 'MMF21370-USD', 'SCH11326-USD', 'LYRA15447-USD', 'PORT11220-USD', 'OPP-USD', 'KEI-USD',
                 'CLUB16802-USD', 'DLAUNCH-USD', 'DDD19744-USD', 'FON21711-USD', 'BUR-USD', 'VRS20477-USD', 'CASHZ-USD',
                 'CPRX-USD', 'GBSK-USD', 'TPAD-USD', 'MNFT-USD', 'TOM-USD', 'MOL-USD', 'PRP-USD', 'SIENNA-USD',
                 'WANUSDT-USD', 'BONE19086-USD', 'DKT-USD', 'MAIN-USD', 'MNTO-USD', 'DMA-USD', 'TUNE-USD', 'TINU-USD',
                 'WOT-USD', 'SAVG-USD', 'MRHB-USD', 'DECA-USD', 'XDEX-USD', 'HAMS-USD', 'HOME-USD', 'GRIM-USD',
                 'CALO-USD', 'BOTX-USD', 'STZ-USD', 'AWS-USD', 'AVME-USD', 'VIP14562-USD', 'M1VERSE-USD', 'MILLI-USD',
                 'GLINK-USD', 'TBK-USD', 'SNAP15906-USD', 'CVSHOT-USD', 'SUTEKU-USD', 'PLY-USD', 'ZERO15973-USD',
                 'CHB-USD', 'UPXAU-USD', 'DKNIGHT-USD', 'COW13439-USD', 'MPT-USD', 'JOY22104-USD', 'HPNS-USD', 'HE-USD',
                 'NCR-USD', 'CUNI-USD', 'TOURISTS-USD', 'SGLY-USD', 'SKI-USD', 'CHAIN-USD', 'BLT20977-USD', 'HNW-USD',
                 'FOF-USD', 'BNBUP-USD', 'HASH19960-USD', 'NTG-USD', 'CLASH-USD', 'MIS16988-USD', 'CMFI-USD',
                 'FLOOR18440-USD', 'ELONGATE-USD', 'UHP-USD', 'ORT-USD', 'KLIMA-USD', 'VOLT18356-USD', 'RAID18977-USD',
                 'MMO16797-USD', 'MONONOKE-INU-USD', 'DEB14650-USD', 'ANN-USD', 'ULX-USD', 'ALPHA16794-USD', 'CGC-USD',
                 'LUCA17370-USD', 'VEN-USD', 'DUSD19933-USD', 'BTE20341-USD', 'UMG-USD', 'FDM-USD', 'HACHIKO-USD',
                 'HMT-USD', 'NEXUS-USD', 'BSP-USD', 'KOMPETE-USD', 'TEP-USD', 'YMS-USD', 'COB20861-USD', 'BPM-USD',
                 'BUZZ22200-USD', 'SALO-USD', 'MYCE-USD', 'DONA-USD', 'BIGB-USD', 'BSKT-USD', 'XPND-USD', 'YOCO-USD',
                 'BFIC-USD', 'BDT9452-USD', 'CELES-USD', 'SKLAY-USD', 'BSY-USD', 'KAWA-USD', 'SRG20985-USD',
                 'HOUSE-USD', 'XIDO-USD', 'CC-USD', 'PBX18126-USD', 'DICE21262-USD', 'METAPK-USD', 'DPX-USD',
                 'FINS-USD', 'BBBR-USD', 'EXMR-USD', 'BMBO-USD', 'AFIT-USD', 'NFLX7928-USD', 'CLAP-USD', 'ROSN-USD',
                 'BABYZOROINU-USD', 'BLUC-USD', 'COCO-USD', 'HOPE-USD', 'STON-USD', 'VITAL-USD', 'PINK9740-USD',
                 'SAFEBULL-USD', 'NFT11-USD', 'TOMOBULL-USD', 'SMETA-USD', 'AGN-USD', 'ITHEUM-USD', 'WOOP19427-USD',
                 'CWT-USD', 'WHACKD-USD', 'ARB21129-USD', 'MPL17502-USD', 'SHICO-USD', 'XRSHIB-USD', 'OSPD-USD',
                 'DHLT-USD', 'TAUD-USD', 'PEFI-USD', 'SPON-USD', 'FHTN-USD', 'KNOT-USD', 'FONE-USD', 'CHAOS-USD',
                 'HAYYA-USD', 'TKG-USD', 'GTE-USD', 'LUCKY-USD', 'APW-USD', 'ERTHA-USD', 'BANDEX-USD', 'AKITAX-USD',
                 'BYG-USD', 'TIC20503-USD', 'BERAGE-USD', 'RDR-USD', 'MARMAJ-USD', 'REAL14463-USD', 'IMT21128-USD',
                 'UM-USD', 'BTCI-USD', 'WAGMIGAMES-USD', 'XP-USD', 'BOJI-USD', 'WATER21718-USD', 'ANATION-USD',
                 'PDT-USD', 'GG-USD', 'NAO-USD', 'PNDR-USD', 'KPAD-USD', 'DHD-USD', 'OMNIA-USD', 'NFTL20927-USD',
                 'MRNA-USD', 'VN-USD', 'PSOL-USD', 'HERA-USD', 'EPAN-USD', 'CPET-USD', 'ILK-USD', 'IDS-USD', 'MOVD-USD',
                 'CNNS-USD', 'YETI-USD', 'TERN-USD', 'PRED-USD', 'KRRX-USD', 'DRK-USD', 'SPIRAL21904-USD', 'AGAIN-USD',
                 'KBOX-USD', 'GRANX-USD', 'DFL19200-USD', 'G20195-USD', 'MMAI-USD', 'CLIFF-USD', 'GEMG-USD', 'HAO-USD',
                 'PYO-USD', 'TOM-USD', 'MOL-USD', 'PRP-USD', 'SIENNA-USD', 'WANUSDT-USD', 'BONE19086-USD', 'DKT-USD',
                 'MAIN-USD', 'MNTO-USD', 'DMA-USD', 'TUNE-USD', 'TINU-USD', 'WOT-USD', 'ANO-USD', 'MLA-USD',
                 'OWL12238-USD', 'WEB318293-USD', 'BHIVE-USD', 'STATIC-USD', 'ADABEAR-USD', 'CHG-USD', 'SNS-USD',
                 'LUSD19714-USD', 'IZI-USD', 'UCOIN-USD', 'LELE-USD', 'PLCU-USD', 'CRUX-USD', 'VBNT-USD', 'DV-USD',
                 'KARMA5935-USD', 'DEFC-USD', 'DEG-USD', 'OG18401-USD', 'KPHI-USD', 'GM-USD', 'GDDY-USD', 'VOO-USD',
                 'RGOLD-USD', 'VELO20435-USD', 'BABYX-USD', 'HEC-USD', 'ZONE18056-USD', 'CTG-USD', 'KRILL18692-USD',
                 'THR-USD', 'SMRT12917-USD', 'MMF-USD', 'THE22278-USD', 'CATBOY-USD', 'LFG21967-USD', 'MCD-USD',
                 'RON14101-USD', 'SISHI-USD', 'GREEN16655-USD', 'BASHTANK-USD', 'CSHARE17851-USD', 'SHIBGOTCHI-USD',
                 'GOGE-USD', 'BABI-USD', 'SPACE9928-USD', 'L2DAO-USD', 'DFND-USD', 'RYOMA-USD', 'USDB-USD', 'FB-USD',
                 'ACTN-USD', 'TMDS-USD', 'NFTD-USD', 'NFTPUNK20-USD', 'DOJO-USD', 'ROCKETBUSD-USD', 'NFP-USD',
                 'MIKU-USD', 'PERC-USD', 'BKN21268-USD', 'MARS10826-USD', 'STC17228-USD', 'OCTF-USD', 'CJET-USD',
                 'LWC-USD', 'MMAON-USD', 'KENSHI-USD', 'LBR-USD', 'LOVE20253-USD', 'CASTLE-USD', 'DUO20312-USD',
                 'MOVE11603-USD', 'SHOES-USD', 'JAM-USD', 'PAW-USD', 'DIGAU-USD', 'WROSE-USD', 'BLINU-USD',
                 'PINU15516-USD', 'MELD13525-USD', 'ZHT-USD', 'LIZARD-USD', 'INU20860-USD', 'MUSK17912-USD',
                 'BURN21068-USD', 'DIAMOND-USD', 'METO16914-USD', 'FVT-USD', 'FUSDT-USD', 'WOLFY-USD', 'TRV20184-USD',
                 'XSB-USD', 'JUB-USD', 'TOR-USD', 'ECELL-USD', 'WSHIB-USD', 'VERSE-USD', '1SWAP-USD', 'PLCU-USD',
                 'CRUX-USD', 'VBNT-USD', 'DV-USD', 'KARMA5935-USD', 'DEFC-USD', 'DEG-USD', 'OG18401-USD', 'KPHI-USD',
                 'GM-USD', 'GDDY-USD', 'VOO-USD', 'RGOLD-USD', 'VELO20435-USD', 'BABYX-USD', 'HEC-USD', 'ZONE18056-USD',
                 'CTG-USD', 'KRILL18692-USD', 'THR-USD', 'SMRT12917-USD', 'MMF-USD', 'THE22278-USD', 'CATBOY-USD',
                 'LFG21967-USD', 'MCD-USD', 'RON14101-USD', 'SISHI-USD', 'GREEN16655-USD', 'BASHTANK-USD',
                 'CSHARE17851-USD', 'SHIBGOTCHI-USD', 'GOGE-USD', 'BABI-USD', 'SPACE9928-USD', 'L2DAO-USD', 'DFND-USD',
                 'RYOMA-USD', 'USDB-USD', 'FB-USD', 'ACTN-USD', 'TMDS-USD', 'NFTD-USD', 'NFTPUNK20-USD', 'DOJO-USD',
                 'ROCKETBUSD-USD', 'NFP-USD', 'MIKU-USD', 'PERC-USD', 'BKN21268-USD', 'MARS10826-USD', 'STC17228-USD',
                 'CJET-USD', 'OCTF-USD', 'LWC-USD', 'MMAON-USD', 'KENSHI-USD', 'LBR-USD', 'LOVE20253-USD', 'CASTLE-USD',
                 'DUO20312-USD', 'MOVE11603-USD', 'SHOES-USD', 'JAM-USD', 'PAW-USD', 'DIGAU-USD', 'WROSE-USD',
                 'BLINU-USD', 'PINU15516-USD', 'MELD13525-USD', 'ZHT-USD', 'LIZARD-USD', 'ARTEX-USD', 'DON8814-USD',
                 'YSHIBAINU-USD', 'BABY-USD', 'EDEL-USD', 'EMC1-USD', 'GDC-USD', 'PNIXS-USD', 'APE-USD', 'SMRTR-USD',
                 'IDO14728-USD', 'XUSD16108-USD', 'SHIBA22-USD', 'BULLSHIT-USD', 'SADA-USD', 'GREENBIOX-USD',
                 'PSOL-USD', 'HERA-USD', 'EPAN-USD', 'CPET-USD', 'ILK-USD', 'IDS-USD', 'MOVD-USD', 'CNNS-USD',
                 'YETI-USD', 'TERN-USD', 'PRED-USD', 'KRRX-USD', 'DRK-USD', 'SPIRAL21904-USD', 'AGAIN-USD', 'KBOX-USD',
                 'GRANX-USD', 'DFL19200-USD', 'G20195-USD', 'MMAI-USD', 'CLIFF-USD', 'GEMG-USD', 'BREWLABS-USD',
                 'BOSS-USD', 'XTZBULL-USD', 'LGOLD-USD', 'JIG-USD', 'NTB-USD', 'BRICK-USD', 'HERO18189-USD',
                 'STD21431-USD', 'PETS13157-USD', 'CAT15953-USD', 'WCT21098-USD', 'KAWAII-USD', 'MILK15050-USD',
                 'CTY-USD', 'ANTE-USD', 'TITA-USD', 'LADA-USD', 'SURF-USD', 'MARSSHIBA-USD', 'DBD-USD', 'MIMO-USD',
                 'PELE-USD', 'BAFE-USD', 'SIL-USD', 'LIEN-USD', 'SHOP-USD', 'DEFI19059-USD', 'HATCH-USD', 'LOOBR-USD',
                 'ERA22150-USD', 'ELF22153-USD', 'META14378-USD', 'THUG-USD', 'MAGICDOGE-USD', 'SQ-USD', 'ZUMD-USD',
                 'LMT20414-USD', 'COR13064-USD', 'ANO-USD', 'WEB318293-USD', 'QWT-USD', 'MLA-USD', 'OWL12238-USD',
                 'BHIVE-USD', 'ROC-USD', 'STATIC-USD', 'ADABEAR-USD', 'CHG-USD', 'SNS-USD', 'LUSD19714-USD', 'IZI-USD',
                 'UCOIN-USD', 'LELE-USD', 'UMG-USD', 'TEP-USD', 'YMS-USD', 'COB20861-USD', 'BPM-USD', 'BUZZ22200-USD',
                 'SALO-USD', 'BIGB-USD', 'BSKT-USD', 'XPND-USD', 'MYCE-USD', 'DONA-USD', 'YOCO-USD', 'BFIC-USD',
                 'BDT9452-USD', 'CELES-USD', 'SKLAY-USD', 'BSY-USD', 'KAWA-USD', 'TRBL-USD', 'TRV20184-USD', 'XSB-USD',
                 'JUB-USD', 'TOR-USD', 'ECELL-USD', 'WSHIB-USD', 'VERSE-USD', 'HEEL-USD', '1SWAP-USD', 'VIZSLASWAP-USD',
                 'RAIN-USD', 'EFIL-USD', 'CAR-USD', 'GAINS-USD', 'WAIFER-USD', 'CCD-USD', 'BLN-USD', 'SHIBELON-USD',
                 '0XT-USD', 'FFT-USD', 'QBT11414-USD', 'SLOKI-USD', 'MF18741-USD', 'BBL-USD', 'GIV-USD', 'MGT13374-USD',
                 'XWIN-USD', 'GFNC-USD', 'MBET-USD', 'ANPAN-USD', 'FLOOF-USD', 'EGG10723-USD', 'SQUIRT-USD', 'FFYI-USD',
                 'SIGN13740-USD', '3CRV-USD', 'TARI-USD', 'UCOIL-USD', 'LDDP-USD', 'DEUX-USD', 'CX1-USD', 'DODI-USD',
                 'ARKN-USD', 'TORG-USD', 'LED14240-USD', 'M87-USD', 'KSHIB17630-USD', 'EQX-USD', 'EAGLE-USD', 'PHL-USD',
                 'D11-USD', 'NPAS-USD', 'KNG-USD', 'CBS-USD', 'JYC-USD', 'DOLA-USD', 'USDZ-USD', 'NOID-USD', 'CDEX-USD',
                 'WALV-USD', 'KCLP-USD', 'APES18987-USD', 'SFO-USD', 'ABEY-USD', 'XPRO-USD', 'DUN-USD', 'EVRF-USD',
                 'MASKDOGE-USD', 'ETHBTCRSI-USD', 'MONEYRAIN-USD', 'AVDO-USD', 'AMPLIFI-USD', 'STORM-USD', 'GTF-USD',
                 'WMOVR-USD', 'NS-USD', 'NISHIB-USD', 'STMAN-USD', 'PATH19288-USD', 'GZX-USD', 'LEO12113-USD',
                 'MOV-USD', 'BULL12961-USD', 'BOOST11216-USD', 'IXT17131-USD', 'PERRY-USD', 'OHM-USD', 'ZOO11556-USD',
                 'ANI-USD', 'GREYHOUND-USD', 'MIKABOSHI-USD', 'PTX-USD', 'METAL21769-USD', 'SMC20348-USD', 'GAMER-USD',
                 'RBP-USD', 'MU19637-USD', 'ELTG-USD', 'VALK-USD', 'CADINU-USD']
